### ISSUE TITLE
Provide ability to add custom beginUpload() functionality for adf-upload-drag-area through Extensions

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#1013]
**Is your feature request related to a problem? Please describe.**
Provide ability to add custom beginUpload() functionality for adf-upload-drag-area through Extensions
**Describe the solution you'd like**
Currently no beginUpload() handle provided in content app and we need to modify directly files component to implement this. Ideally all the parameters to the adf components should be parameterized so that we can modify through extensions. 
**Describe alternatives you've considered**
Provide the customizataions for all the possible parameters of adf components
**Additional context**

**Comment by inavarre** [comment]
@nvmadhav Is this something that is still valid for you?
