### ISSUE TITLE
Refresh document list to show the lock as soon as user clicks on "Edit In Microsoft Office"

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#1020]
**Describe the bug**
When user clicks on "Edit in Microsoft Office", he has to refresh the document list manually to see the lock. Ideally this should happen automatically as soon as user clicks on "Edit in microsoft office"
**Environment**
- ACA version: [e.g. 1.6] 1.6
- ACS version: [e.g. 6.1] 5.2

**To Reproduce**
1. Go to word document
2. Click on "Edit in Microsoft Office"
3. In the document list file didn't show as locked
4. Refresh the screen and you see the lock

**Expected behavior**
Ideally we should reload the document list so that user sees the change
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by john-knowles** [comment]
Thank you for the feedback.
@DenysVuika - is this dependant on ADF https://issues.alfresco.com/jira/browse/ADF-3794 ?

**Comment by DenysVuika** [comment]
Yes, if that feature gets into ADF 3.1 then we will be able to address this issue.

**Comment by john-knowles** [comment]
Thank you - https://issues.alfresco.com/jira/browse/ACA-2289

**Comment by john-knowles** [comment]
Closing this issue, since there is no way for the platform to communicate this back to the user interface.
