### ISSUE TITLE
Quick content view of the versions

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#1021]
**Is your feature request related to a problem? Please describe.**
Currently if user wants to view the content of a version, he/she should download that version to preview. Ideally users should have ability to view the content of version without downloading the document.
**Describe the solution you'd like**
Provide quick preview of the versions content in Manage Versions.

**Describe alternatives you've considered**

**Additional context**

**Comment by john-knowles** [comment]
The repository does not support this feature.
Please log a request with Alfresco Customer Support (reference REPO-142)
