### ISSUE TITLE
Provide group memberships for ContextRule

### ISSUE THREAD

**Issue by rderooij** [Alfresco/alfresco-content-app#1067]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The goal is to show/hide menu items in the navbar based on group memberships of the logged in user.

When implementing an evaluator I want to validate on the groups the user is member of. The ContextRule.profile does not provide enough information about the user. Also the AuthenticationService does not provide this information.

Implementing the peopleApi (or any other api) within the evaluator function will not work because of the asynchronous behaviour. The menu page is already loaded when receiving the response of the api call. 

## Expected behavior

Able to validate on group memberships.

## Environment

<pre><code>
ACA version: 1.7.0

Browser:
- [x ] Chrome version XX
- [ x] Firefox version XX
- [x ] Safari version XX
- [x ] Edge version XX
- [x ] IE11
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by john-knowles** [comment]
Thank you @rderooij - I have placed this into our backlog: https://issues.alfresco.com/jira/browse/ACA-2351

**Comment by DenysVuika** [comment]
Added in the development branch and will be available with 1.8.0
