### ISSUE TITLE
Document list not retaining the page state

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#1076]
**Describe the bug**
In content app, if we are on the second page of the document list, and if we preview a file and close the preview component, document list resetting to the first page and not retaining the page where the users was on.
**Environment**
- ACA version: [e.g. 1.6] 1.7
- ACS version: [e.g. 6.1]

**To Reproduce**
1. Go to Favorites
2. Navigate to second page
3. Click on a file to preview
4. Close the file preview and you observe, user is back on the first page but not on the second page.

**Expected behavior**
Ideally user should be on the page he is navigated to.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adinapitul** [comment]
Issue is fixed in ACA 1.9
