### ISSUE TITLE
Execute Web Script scriptArgs argument is fixed to string in alfresco-content-app 3.0.0 

### ISSUE THREAD

**Issue by annapatonova** [Alfresco/alfresco-content-app#1083]
**Describe the bug**
I used to call repository webscript to get document version (/alfresco/s/api/version) like this :

```
 this.apiService.getInstance().webScript.executeWebScript(
                    'GET',
                    'api/version',
                    { 'nodeRef': 'workspace://SpacesStore/' + this.nodeId },
                    "alfresco",
                    "s").then((webScriptdata) => {
                        this.versionLabel = webScriptdata[0]["label"];

....
....
                        });
```
It works fine in 2.6.0 cause in _webscript.api.ts_ **scriptArgs** parameter is of any type :
` executeWebScript(httpMethod: string, scriptPath: string, scriptArgs: any, contextRoot: string, servicePath: string, postBody?: any)`

I have a problem with 3.0.0 cause in _webscript.api.ts_ **scriptArgs** parameter is of string type :
 `executeWebScript(httpMethod: string, scriptPath: string, scriptArgs: string, contextRoot: string, servicePath: string, postBody?: any)`
And when I pass this param as a string : 
`scriptArgs=" { 'nodeRef': 'workspace://SpacesStore/' + this.nodeId }" `
The code after don't parse properly my paramter.  

**Environment**
- ACA version: 3.0.0
- ACS version: 5.2.4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 73

**Comment by DenysVuika** [comment]
@annapatonova ACA does not provide any custom webscript apis, you may need to raise the issue for the JS-API project. 

Also, according to the API, the format of the parameter is "any", not "string" https://github.com/Alfresco/alfresco-js-api/blob/development/src/api/content-rest-api/api/webscript.api.ts#L51.

**Comment by annapatonova** [comment]
@DenysVuika Thank You, I found the corrresponding issue in JS-API project(https://github.com/Alfresco/alfresco-js-api/issues/394) .
