### ISSUE TITLE
Docker entrypoint.sh is missing sed-safe encoding for APP_BASE_SHARE_URL

### ISSUE THREAD

**Issue by AFaust** [Alfresco/alfresco-content-app#1127]
**Describe the bug**
The Docker entrypoint.sh script does not encode the value of APP_BASE_SHARE_URL before performing value injection into app.config.json. Even when providing the default value as an env variable, there will be an (ignored) error during container startup:

```sed: bad option in substitution expression```

**Environment**
- ACA version: 1.7
- ACS version: irrelevant

**To Reproduce**
1. Start the alfresco/alfresco-content-app:master-latest image with the APP_BASE_SHARE_URL value set to any string that includes a /, e.g. http://my.host.tld/content-app/#/preview/s
2. Retrieve container logs
3. Access app.config.json inside instantiated container

**Expected behavior**
No error should occur during container initialisation.
Value of APP_BASE_SHARE_URL  should be injected into app.config.json

**Comment by john-knowles** [comment]
Thank you raising this Axel!

**Comment by john-knowles** [comment]
JIRA ticket: ACA-2470
