### ISSUE TITLE
Link Generated from share action redirects to login page, when authentication is OAUTH.

### ISSUE THREAD

**Issue by rohit9637** [Alfresco/alfresco-content-app#1139]
**Describe the bug**
Link Generated from share action redirects to the login page when authentication is OAUTH. Whereas it works fine if Authentication is BASIC

**Environment**
- ACA version: [e.g. 1.7]
- ACS version: [e.g. 6.1]

**To Reproduce**
1. Set Auth to OAuth from app.config.json
2. Go to 'file library'
3. Click on 'share' action
4. Follow the link in the new incognito tab.
5. You get redirected to login.

**Expected behavior**
Should not redirect to Login

**Comment by john-knowles** [comment]
Thank you @rohit9637 - we'll take a look at this and plan into a future release.

**Comment by john-knowles** [comment]
Closing this issue in preparation for the 1.9 release.
