### ISSUE TITLE
The content app is not working in Internet Explorer

### ISSUE THREAD

**Issue by ShivaniNR** [Alfresco/alfresco-content-app#1147]
**Describe the bug**
The Alfresco Content App is not working on IE.

**Environment**
- ACA version: 1.7
- ACS version: [e.g. 6.1] 

**To Reproduce**
1. Start the application.
2. Go to IE.
3. See error.

**Expected behavior**
The application should be visible on the browser without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/47320667/60649647-03d74780-9e60-11e9-8355-ea7e59af67c5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: IE
 - Version: 11

**Comment by DenysVuika** [comment]
We do not support IE11. You can grab the source code and try adding the required polyfills but we are not going to penalise the rest of the world with big bundles out of the box.
