### ISSUE TITLE
Different response time on different computers

### ISSUE THREAD

**Issue by ProfEibe** [Alfresco/alfresco-content-app#1155]
On latest aca version.

I hope someone can help me, because I don´t know what´s the reason.

I´ve setup ACA on two different computer by building it from source. On one of them everything runs really fast and smooth on the other one it takes a few seconds after each click.

```
git clone https://github.com/Alfresco/alfresco-content-app.git
cd alfresco-content-app
npm install
npm start
```

Also simple browsing through folders takes this amount of time. And when I click on one folder to open it, it first shows me that it is empty, then after a second or two a loading screen and after that the content.

I have cloned it again and restartet my setup, but it did not chang anything. Using the old alfresco client works really good and fast, so it can´t be the connection to the server.
Is there maybe anything i´ve installed what slows down the application? I´ve tried the old setup before on the slow computer. can this be the problem? (https://www.alfresco.com/abn/adf/docs/tutorials/creating-your-first-adf-application/)

I hope someone understands my issue and can help me. 
Thanks in advance

**Comment by DenysVuika** [comment]
Hello, I have a few questions/concerns regarding this ticket

- What does the "latest aca version" mean? Does it have a version number?
- What mode you are using: production/development
- How you run it: local, docker, remote, etc
- Proxy details?
- No information about OS/browser/etc spec

I am closing this issue as it gives absolutely no information/clues on how to troubleshoot it. Please reopen it with more details or provide a new ticket.

**Comment by adinapitul** [comment]
I think the ACS version behind ACA is also important. 
- ACS version?
- where is ACS installed?
- the 2 ACA installations point to the same ACS or to 2 different ones?

**Comment by ProfEibe** [comment]
is ACS the alfresco server? or something different?
It is installed on a local server in our company. And both application use the same one.

ACA is 1.8.0 the latest from the master branch in github. I have just done the 4 steps from my previous post and changed the server in proxy.conf.js, so it should be in development mode i think. and i´ve tried it in firefox and chrome

**Comment by ProfEibe** [comment]
Solution maybe for the future.

The problem was Windows 10. I was using a DomainName instead an IP Adress to link to my Alfresco Server. Windows 10 need much longer to get the IP Adress than for example Windows 7.

So changing the Domain to the IP Adress in proxy.conf.js solved my Problem. Always use the IP and no Domain if possible.
