### ISSUE TITLE
The link to the document is incorrect.

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/alfresco-content-app#1176]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There are some links that do not transition to the official document of Alfresco Development Framework.
When the link is clicked, "Page not found." Is displayed.

## Expected behavior

When you click the link, it will transition to the official document of Alfresco Development Framework.

## Minimal reproduction of the problem with instructions

In the "docs/features/search-results.md" document, clicking the "Search Filter" link results in an error.
This is because the URL path is different, and there are several other Markdowns.

## What is the motivation / use case for changing the behavior?

By correcting this, you can get the right information.

## Environment

<pre><code>
ACA version: X.Y.Z

Browser:
- [ ] Chrome version XX
- [x] Firefox version 68.0.1
- [ ] Safari version XX
- [ ] Edge version XX
- [ ] IE11
 
For Tooling issues:
- Node version: 10.16.0
- Platform:  Mac

Others:

</code></pre>

**Comment by adinapitul** [comment]
PR was merged. Closing the issue.
