### ISSUE TITLE
Japanese Documentation.

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/alfresco-content-app#1178]
**Is your feature request related to a problem? Please describe.**

I'm focusing on an ready-to-use ADF app, but the official documentation is important because it has less information than I think.
Localizing official documents can be expected to promote the use of ADF apps.

**Describe the solution you'd like**

Create localized document.

**Describe alternatives you've considered**

We are also considering localization as a third party. However, they are concerned about legal issues such as licensing and copyrights.

**Additional context**
None.

**Comment by DenysVuika** [comment]
The ACA is not supported application, but you can contribute the translations of the documentation if you like so that other community members benefit too.

**Comment by john-knowles** [comment]
Documentation for our supported version, known as Alfresco Digital Workspace, can be found here in Japanese: https://docs.alfresco.com/adw-ja/concepts/welcome-adw.html

**Comment by silverskyvicto** [comment]
Sorry for late reply.

@DenysVuika 
Thank you for your comment.
There is an ACA document translated into Japanese. Should I propose a translated document with a pull request?

@john-knowles 
I didn't know that the Enterprise version has Japanese documents.
I will refer to it.

**Comment by DenysVuika** [comment]
Yes, can create PR with the translated content, thanks.

**Comment by silverskyvicto** [comment]
@DenysVuika 
I created a "ja" directory under the "docs" directory and put the contents in it.

**Comment by suzanadirla** [comment]
Until the ACA 1.9 is released, the Japanese version of the documentation can be accessed from here: https://aca-dev-docs.netlify.com/#/
Thank you, @silverskyvicto for your contribution!
