### ISSUE TITLE
Content metadata card preset does not work as documented

### ISSUE THREAD

**Issue by jpotts** [Alfresco/alfresco-content-app#1190]
**Describe the bug**
If you add an additional preset to app.config.json as described in this tutorial (https://www.alfresco.com/abn/adf/docs/tutorials/content-metadata-component/) and then edit metadata-tab.component.ts to change the preset from "custom" to "my-preset", the additional preset does not get displayed.

**Environment**
- ACA version: 1.9.0
- ACS version: 6.1.0.5 Enterprise

**To Reproduce**
Edit the presets in app.config.json to add:
      "my-preset": [
        {
          "title": "This is my preset",
          "items": [
            {
              "aspect": "st:siteContainer",
              "properties": ["*"]
            }
          ]
        }
      ]

Edit metadata-tab.component.ts to change the preset from default to my-preset:
    <adf-content-metadata-card
      [readOnly]="!canUpdateNode"
      [preset]="'my-preset'"
      [node]="node"
      [displayAspect]="displayAspect$ | async"
    >

**Expected behavior**
Expected to see "This is my preset" listed in the metadata tab. Instead, when you click "Less Information" you will see "Properties", "Tag Scope", "Site Container", "Titled" and "Ownable". In fact, that is what will be shown if you use any value for preset other than "custom" even if the specified preset does not exist in app.config.json.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Firefox
 - Version: 68.0.2

**Comment by dhrn** [comment]
Metadata card Preset values are taken from `app.extensions.json`, not `app.config.json`

https://github.com/Alfresco/alfresco-content-app/blob/development/src/assets/app.extensions.json#L1022

**Comment by jpotts** [comment]
I guess this tutorial needs to be updated, then: https://www.alfresco.com/abn/adf/docs/tutorials/content-metadata-component/

I recognize that is an ADF link, not an ACA link. Maybe rather than linking me to a general page on extensions, you could link me to the specific docs related to customizing the info drawer.

**Comment by dhrn** [comment]
Basically you need this kind of JSON -> https://github.com/Alfresco/alfresco-content-app/blob/development/src/assets/plugins/app.metadata.json

Add the desired aspect and properties to the JSON

finally, refer your JSON to extension.json like this -> https://github.com/Alfresco/alfresco-content-app/blob/development/src/assets/app.extensions.json#L10

Then you will be able to see the aspect.

**Comment by dhrn** [comment]
here is the doc link -> https://alfresco-content-app.netlify.com/#/extending/application-features

**Comment by adinapitul** [comment]
Closing the issue. Please reopen if you consider the docs are still not clear enough.

**Comment by dsvmacdonald** [comment]
content-metadata works fine in app.config.json.  I'm guessing the issues was that the search configuration for the SearchQueryBuilderService was missing stuff in app.config.json.  

Make sure to set search like:

search: {
...
"include": ["path", "properties", "allowableOperations", "aspectNames"],
...

Important parts are "properties" and "aspectNames"

**Comment by dhrn** [comment]
Hi @dsvmacdonald 
IIRC, app.config is not correct for since ACA 2.5.0 
please checkout here https://alfresco-content-app.netlify.app/#/tutorials/search-form
