### ISSUE TITLE
Enhanced libraries component with search filter

### ISSUE THREAD

**Issue by rohit9637** [Alfresco/alfresco-content-app#1191]
Current ACA version does not support Search, filtering at Library level. This will help to find documents with ease and speed.
Let's consider a folder has thousands of documents and with the current implementation, it will be difficult to find and locate the file, when user increase the pagination size(100 or more).

**The solution description**

Libraries component can be enhanced by adding the filters on the top of it.

There would be the following filters:

1. Name: Basically a search box which will search only in the library. Ignore checklist from mockups
2. File Type: A search box with typeahead/autocomplete field, which will show checklist on search. User should be able to select multiple checklist items. The data for typeahead/autocomplete could be taken from document list data.
3. File Size: Checklist showing size range same as the categories from the search component.
4. Author: Typeahead/autocomplete text box with a checklist same as Filter Type
5. Date: This will have date range for date created and date modified.

Filter to be excluded from below provided mockups.

1. Content-Type

All the search filter will be on the library level, which will be applied to library data. No Solr query should be used.
The search will be on documents on the same page, from pagination.

Following are the screenshots from the mockup

![libraries](https://user-images.githubusercontent.com/34914213/63944324-f10f7680-ca8e-11e9-9c37-529fbddaa2ec.png)
![libraries-filter](https://user-images.githubusercontent.com/34914213/63944322-f10f7680-ca8e-11e9-92ab-5399d3c6a94d.png)
![name-filter](https://user-images.githubusercontent.com/34914213/63944457-2916b980-ca8f-11e9-9b85-0097e2863e7c.png)
![file-type-filter](https://user-images.githubusercontent.com/34914213/63944320-f076e000-ca8e-11e9-8df0-c2d46eae15ac.png)
![size-filter](https://user-images.githubusercontent.com/34914213/63944318-f076e000-ca8e-11e9-8189-bd1d4a8d49f1.png)
![author-filter](https://user-images.githubusercontent.com/34914213/63944317-efde4980-ca8e-11e9-8f3d-2b6b4cbf03a8.png)
![date-filter](https://user-images.githubusercontent.com/34914213/63944326-f1a80d00-ca8e-11e9-8605-ac5bf393ec8b.png)

**Comment by rohit9637** [comment]
@DenysVuika did you reviewed this?
Can we get a go-ahead for this?

**Comment by DenysVuika** [comment]
@rohit9637 do you want to provide the component enhancements? I believe the mockups require changing the behavior and code of the ADF part (document list, datatable) as well as pagination and loading logic.

**Comment by rohit9637** [comment]
@DenysVuika yes, enhancing the component used for libraries of ACA.
What do you think of the feature? It is feasible? What changes would be needed in ADF code? Should I create the same feature request in ng2-component git?

**Comment by DenysVuika** [comment]
@rohit9637 are you willing to contribute all the code to make those designs work?

**Comment by rohit9637** [comment]
Yes.

**Comment by DenysVuika** [comment]
@rohit9637 you can create a feature request on the ADF part and mark that you will create a PR with the changes. Or you can create a wrapper component at your side and add extra filtering capabilities.

**Comment by eromano** [comment]
@rohit9637 I really like it 👍

**Comment by rohit9637** [comment]
@DenysVuika the feature request will be the same as this or do I need specifies detailed feature request for each component as you mentioned (document list, datatable) as well as pagination?

**Comment by DenysVuika** [comment]
@rohit9637 I think the same one if more than enough

**Comment by mauriziovitale** [comment]
@rohit9637 this is a great idea, but in my opinion, these filters should be part of an advance search panel and not be a concern of the document list

**Comment by rohit9637** [comment]
@mauriziovitale but by advanced search is it possible to address the issue in search document per folder?

**Comment by mauriziovitale** [comment]
@rohit9637 why do you care about the folder? If your folder contains 1000 items means that your query wasn't precise. Are you trying to filter the data on the client-side?

**Comment by mauriziovitale** [comment]
this means that if you are filtering by author and there are other images/docs of that author in another page, you won't see those.

**Comment by rohit9637** [comment]
Yes, filter will be applied to the same page. It can be of size 100, 200, 500.

**Comment by john-knowles** [comment]
Looks like a lot of thought has gone into this, I like it too.  For use cases where there are a large number of files in one folder filtered in the document list like this will help them find their files much more quickly.  I look forward to see this come through from the Alfresco ADF soon.  Well done so far @rohit9637 

@mauriziovitale - you're not wrong, Advanced Search, via a form or some other UI is something that would benefit this app and the ADF.  I think the problem @rohit9637 is trying to solve here is that the user knows roughly where an item is, and they want to quickly narrow down the contents of the folder.

Another approach to this could be to enhance the applications Search Input box to do "Search in this folder", bit like this:

![image](https://user-images.githubusercontent.com/18680913/64861621-4c616d00-d628-11e9-93d4-f91b95bcc472.png)

**Comment by inavarre** [comment]
Closing as this is duplicated in the ADF project - https://github.com/Alfresco/alfresco-ng2-components/issues/5074
