### ISSUE TITLE
Conditionally hiding/enabling the side-navigation group items.

### ISSUE THREAD

**Issue by ShivaniNR** [Alfresco/alfresco-content-app#1192]
**Is your feature request related to a problem? Please describe.**
Yes, could not hide/enable the side-nav group items based on extensions. For eg, when we need extension-specific side-nav group items. 

**Describe the solution you'd like**
Able to display the side-nav group items conditionally by enabling/disabling it through the extension's plugin file.

**Describe alternatives you've considered**
Alternative considered was to disable the default side-nav group items and enable the extension-specific side-nav group items based on the route URL.

**Additional context**
Currently, it is being displayed as shown in the attached screenshot. 
![image](https://user-images.githubusercontent.com/47320667/64153619-db160300-ce4c-11e9-9e20-0aea7fdb5e6f.png)
All the group items are being displayed one after another for all the extensions.

**Comment by pionnegru** [comment]
@ShivaniNR can you update your development and checkout this issue again?

**Comment by ShivaniNR** [comment]
@pionnegru, could you please provide the documentation for the added feature?

**Comment by pionnegru** [comment]
https://deploy-preview-1197--aca-dev-docs.netlify.com/#/getting-started/navigation?id=rendering-custom-components

**Comment by pionnegru** [comment]
@ShivaniNR ^

**Comment by pionnegru** [comment]
@ShivaniNR does this new features helped you with your case?

**Comment by ShivaniNR** [comment]
@pionnegru, yes. 
Thanks for providing this feature!
