### ISSUE TITLE
Alfresco Content App Edit in Microsft Office Change Effect Time

### ISSUE THREAD

**Issue by ysngrmz** [Alfresco/alfresco-content-app#1243]
In alfresco content app, we are using ACA 1.8 and ACS 6.2. 
Alfresco doesn't see changes instantly when you make changes with Microsoft office.

For example, if you edit a alfresco .docx file using Microsoft office, Alfresco content-app still showing the old version of document. After about 25 minutes, alfresco content-app start to showing editted version. 
We also try it using ACA 1.9 still change effect the render about 25 minutes. 

**To Reproduce**

- Go to a word document
- Click on "Edit in Microsoft Office"
- Modify the word document 
- Save the document and  Click on "View" in alfresco, still it shows old version
- After about 25 minutes, it starts t showing new version

Is there any way to make this evet instatly or is there any way to change effect time.

**Comment by john-knowles** [comment]
ACA is not processing anything, once the file is updated in the Content Repository then a PDF rendition is created.  What you are describing sounds like your transformations are slow.

Do you see the same behaviour if you just upload a new version?

**Comment by ysngrmz** [comment]
I only see that behaviour, while editing microsft office. 
When I just uplad new version, it add -1 to name of it and shows both of them in document list. 
For example, if there is a.docx and I drag a drop to new a.docx. It change the name of it to a-1.docx and both a.dox and a-1.docx showed in file list.

**In addition, If fallow these steps :** 

- Go to a word document
- Click on "Edit in Microsoft Office"
- Modify the word document
- Save the document and Click on "View" in alfresco
- It still shows the old version but If a say download on pdf renderer it downloads the new version

**Comment by john-knowles** [comment]
Sounds you are not uploading a new version, you are uploading a new file if the name is appended with "-1".

To upload a version, **right click** on the file, and select the **Upload new version** action to upload a new version.

**Comment by ysngrmz** [comment]
When I upload new version, I face withsame problem

**Comment by ysngrmz** [comment]
Could you tell me how can I change my transformation settings

**Comment by john-knowles** [comment]
This project is focused on the front end app which interacts with the API layer of Alfresco.  Please contact Alfresco Support or head over to the Alfresco Community: https://hub.alfresco.com.
