### ISSUE TITLE
Icon alignment mismatch

### ISSUE THREAD

**Issue by dhrn** [Alfresco/alfresco-content-app#1256]
**Describe the bug**

**Environment**
Development branch

**To Reproduce**
![image](https://user-images.githubusercontent.com/14145706/69406835-08c26800-0d29-11ea-8a69-04b0cc9897c2.png)

Upload the file with the same name 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [linux mint]
 - Browser [Chrome]
 - Version [78]

**Additional context**

**Comment by adinapitul** [comment]
Thank you for your submission. Issue now raised and will be tracked here: https://issues.alfresco.com/jira/browse/ACA-2829
