### ISSUE TITLE
browser language issue

### ISSUE THREAD

**Issue by aloufi** [Alfresco/alfresco-content-app#1276]
**Describe the bug**
We have an employee who has Korean language in his chrome browser. When view the documents list one document only viewed and in the middle of the page. 

**Environment**
- ACA version: 1.8.0

**To Reproduce**
1. change the chrome browser language to Korean.
2. Click on personal files or site files
3. See error

**Expected behavior**

**Screenshots**
![issue](https://user-images.githubusercontent.com/7574815/70599600-8bd72f80-1bfe-11ea-9e12-fc502c6329de.PNG)

**Desktop (please complete the following information):**
 - Browser [chrome]

**Additional context**
I fixed this issue by adding 
`registerLocaleData(localeKo);`
in app.module.ts

**Comment by DenysVuika** [comment]
Your solution is correct, calling `registerLocaleData` is required by Angular, that is not a bug.
