### ISSUE TITLE
Search Result Component

### ISSUE THREAD

**Issue by uvukasinovic** [Alfresco/alfresco-content-app#1278]
**Describe the bug**
Search tag by name isn't possible because ACA code creates query with `TAG:"searchTerm*"`. 
When '*' is removed, search by tag name is possible.

There are defined 'aca:fields' in app.config.json. Those fields are formatted in search-results.component.ts, where '*' is added as suffix to every field from 'aca:fields'. Because of that, we have `TAG:"searchTerm*"`.

Problematic method in search-results.component.ts:
`private formatFields(fields: string[], term: string): string`

Alfresco fts-alfresco search `TAG:"searchTerm*"` in ACS 5.2 gives 0 results. When '*' is removed from end, we have good results. Valid query is: `TAG:"searchTerm"`. That query should be also created in ACA code.

**Environment**
- ACA version: [e.g. 1.9.0]
- ACS version: [e.g. 5.2]

**To Reproduce**
1. Go to ACA application
2. Add tag on content
3. Put tag name in search input
4. Content will not be found in search results

**Expected behavior**
Content should be found by tag name.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 78.0.3904.108

**Comment by mmuller88** [comment]
Hi uvu . 
Thank you so much for the feedback. My question:
How do you add the Tag?

Cheers

**Comment by mmuller88** [comment]
Try 
TAG:searchTerm*
You see don't use the double apostrophe :)

**Comment by uvukasinovic** [comment]
> Hi uvu .
> Thank you so much for the feedback. My question:
> How do you add the Tag?
> 
> Cheers
Thanks for the reply.

I can add tag via developed Tag Content action or via ACS.

But, the point is, when you add Tag on content, you can't search content by tag name in ACA.

**Comment by mmuller88** [comment]
Mhh I may misunderstood. I added a tag "abc" with using Share and I could find the node with TAG:ab*

**Comment by pionnegru** [comment]
@uvukasinovic can you explain more what does 'can't search content by tag' means so we can eliminate further confusions?

**Comment by mmuller88** [comment]
TAG:ab* AND TYPE:"cm:content"

works as well.

**Comment by uvukasinovic** [comment]
For example, you have a document in ACA, "test.docx". You add a tag on that document, let say tag: "officeDocument". 

In ACA, if you put in search input -> officeDocument, you will not have test.docx document as a search result.

Search by tag name in ACA isn't provided. I found the reason and in my opinion, it's a bug. Please take a look above in the description of the issue or if try to search content by tag name and you will see what is the root of the problem.

**Comment by uvukasinovic** [comment]
I tried now TAG:officeDocument* in search input and it works. I didn't now that in ACA we have also query possibility in the search input. 

Sorry for the false alarm and thanks for quick response,

**Comment by pionnegru** [comment]
we support a template to define complex queries

**Comment by mmuller88** [comment]
Cool glad that we could help ya :)
