### ISSUE TITLE
Microsoft Office edit button does not work on documents in Application Content shared area

### ISSUE THREAD

**Issue by mhmmderen3** [Alfresco/alfresco-content-app#1326]
Microsoft Office edit button does not work on documents in Application Content shared area
We are using following versions

ACS 6.2

ACA 1.9

Docker 19.03.5

Kubernetes 1.14.6

Helm 2.14.3

ActiveMQ 5.15.8

Alfresco Search 1.4.0

I can edit the document in the folder where I have administrative authority with Microsoft Office, but I can't do it in the shared space and favorite area.

![screenshot-docs detaysoft com-2020 01 29-23_29_40 (1)](https://user-images.githubusercontent.com/45883661/73442508-081c0280-4366-11ea-8ccd-4f7a6fb6e640.png)

**Comment by pionnegru** [comment]
this is fixed in ACA 1.10.0
