### ISSUE TITLE
content property appear in custom model

### ISSUE THREAD

**Issue by aloufi** [Alfresco/alfresco-content-app#1337]
**Describe the bug**
when click update metadata in custom model there will be property called "Content" if update this property error msg will be shown and the site no longer accessible even from share.

**Environment**
- ACA version: [1.8]
- ACS version: [6.1]

**To Reproduce**
1. change any file to custom type e.g. acme:document.
2. Click on view details and click on edit.
3. update Content property.
4. click save.
5. popup error will appear.

**Expected behavior**
I don't think Content property should appear.

**Screenshots**

![error](https://user-images.githubusercontent.com/7574815/74228683-fb869b00-4cd1-11ea-821d-b0bf2397686a.png)

**Additional context**
here is the logs file 
[debug.log](https://github.com/Alfresco/alfresco-content-app/files/4185097/debug.log)

also how to fix site has this issue.

**Comment by ellerMitte** [comment]
I think it's not a bug. You can define visibility of properties and aspects in app.config.json file. More details you can find [here](https://www.alfresco.com/abn/adf/docs/content-services/components/content-metadata-card.component/).

**Comment by inavarre** [comment]
@aloufi  is this still an issue for you? Did you have a look at the docs in mentioned in the comment above?

**Comment by aloufi** [comment]
It’s worked as @ellerMitte suggested
