### ISSUE TITLE
Create from template

### ISSUE THREAD

**Issue by isainz753** [Alfresco/alfresco-content-app#1402]
**Describe the bug**
Options New / Create file or folder from template bug message. 
"The action was unsuccessfull. Try again or contact your IT Team."

**Environment**
- ACA version: 1.10 and latest
- ACS version: 5.2 and latest

**Expected behavior**
Previously i am  select folder node in reporitory.
I have files and folders into Data Dictionary templates folder

**Screenshots**
![alfrescoADFBug](https://user-images.githubusercontent.com/20379591/78637993-cb134580-78ab-11ea-8e0f-446d108a7c1b.jpg)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome, etc
 - Version 10

**Comment by inavarre** [comment]
Hello, 

Are you able to provide us with a bit more information, please? 

Can you show us a screenshot of the Network Tab in the Developer Tools when the action is performed so we can see the request that is failing and the response?

**Comment by isainz753** [comment]
Hello,

This is the tail.

Thanks.
![alfrescoADFBug1](https://user-images.githubusercontent.com/20379591/79117763-4aad8280-7d8c-11ea-8c17-a203b27cb9e0.jpg)
![alfrescoADFBug2](https://user-images.githubusercontent.com/20379591/79117764-4bdeaf80-7d8c-11ea-85a0-fa33f094b76f.jpg)
![alfrescoADFBug3](https://user-images.githubusercontent.com/20379591/79117766-4bdeaf80-7d8c-11ea-8a48-c0534fcfe546.jpg)

**Comment by pionnegru** [comment]
@isainz753 can you provide the "Proyecto de ingeniería de software" node path info from Network tab?

**Comment by isainz753** [comment]
Hi,

This is the path.
![alfrescoADFBug1](https://user-images.githubusercontent.com/20379591/79195399-7d0fbc00-7e2e-11ea-9cce-7ffa4459fa0d.jpg)
![alfrescoADFBug2](https://user-images.githubusercontent.com/20379591/79195402-7e40e900-7e2e-11ea-8395-28416c2a9dfe.jpg)

**Comment by isainz753** [comment]
Works Thanks.
