### ISSUE TITLE
Enable Search Filters in the Settings Menu

### ISSUE THREAD

**Issue by shazada** [Alfresco/alfresco-content-app#1451]
**Is your feature request related to a problem? Please describe.**
I'm very irritated that each app needs to be changed via app.config.json or any other json when some settings should be done in a settings.
We release a general ACA app to several customers in Docker for several Enterprise Customers. No we need to build and release each app differently, but in essence it's exactly the same app but with different configurations.
![FireShot Screen Capture #004 - 'Settings - Alfresco Content Application' - demo_tezza_eu](https://user-images.githubusercontent.com/1477763/81274485-a2b86b80-9050-11ea-83cd-c4ec57d52ae5.png)

**Describe the solution you'd like**
We want to be able to release the same app to different customers without changes something in the build.
So either add to the settings page the Search Filters so these can be configured.
Or even better when creating the search filters in share honor them and include them automatically
![FireShot Screen Capture #005 - 'Alfresco » Search Manager' - demo_tezza_eu](https://user-images.githubusercontent.com/1477763/81274602-ced3ec80-9050-11ea-8d22-5581a04d6d14.png)
**Describe alternatives you've considered**
Create custom app.config.json's for each customer and when staring the Docker container override these with the customers
**Additional context**

**Comment by DenysVuika** [comment]
Note that ACA is not a UI on top of Share. It's not calling and not depending on Share, but uses public REST api instead. So "honor Share filters" is not going to work in this case.

Also, the Settings page is an internal route, it is intended for testing and is pure client-side thing. We are going to delete this route at some point in the future.

**Comment by shazada** [comment]
Hi Denys,

Sure I understand, but what we want is some kind of UI configuration in ACA (DW) to enable search filters and define them.

**Comment by DenysVuika** [comment]
@shazada yes, sure, that makes sense. I was just sharing info so that you don't rely on /settings or Share. For sure we will provide something to save your time.
