### ISSUE TITLE
Save / Cancel buttons not supported with i18n (ADF Metadatacard)

### ISSUE THREAD

**Issue by rderooij** [Alfresco/alfresco-content-app#1458]
**Describe the bug**
Save / Cancel buttons are not supported with i18n

**Environment**
- ACA 1.11.0
- ACS 6.2

**Comment by adinapitul** [comment]
Thank you for your submission.
This is already raised internally: [ACA-3252](https://issues.alfresco.com/jira/browse/ACA-3252)

**Comment by dhrn** [comment]
seems fixed [here](https://github.com/Alfresco/alfresco-ng2-components/pull/5737)
