### ISSUE TITLE
Save metadata on folders produce error (ADF metadata card)

### ISSUE THREAD

**Issue by rderooij** [Alfresco/alfresco-content-app#1459]
**Describe the bug**
Using the new metadata card with save and cancel buttons works, but we see the following error when updating folder metadata:

ERROR TypeError: Cannot read property 'sizeInBytes' of undefined

**Environment**
- ACA 1.11.0
- ACS 6.2

**To Reproduce**
1. Go to folder
2. Click on show details
3. Edit title
4. Click save

**Expected behavior**
No errors

**Comment by dhrn** [comment]
feel free to reopen if not fixed
