### ISSUE TITLE
Save / cancel buttons are not active in edit mode (ADF metadata card)

### ISSUE THREAD

**Issue by rderooij** [Alfresco/alfresco-content-app#1460]
**Describe the bug**
The first time you are in edit mode and you want to edit only the name you cannot click on the save button. You have to click somewhere else on the page to activate the buttons. 

**Environment**
- ACA 1.11.0
- ACS 6.2

**To Reproduce**
1. Go to file
2. Click view details
3. Click on Edit
4. Change name 
4. Cannot click on save

**Expected behavior**
Buttons are active when opening the edit component.

**Comment by dhrn** [comment]
raised ticket internally  [ACA-3499](https://issues.alfresco.com/jira/browse/ACA-3499)
