### ISSUE TITLE
Adding ACA as a dependency on Windows it tries to execture "postinstall": "./scripts/postinstall.sh",

### ISSUE THREAD

**Issue by shazada** [Alfresco/alfresco-content-app#1481]
**Describe the bug**
When including alfresco-content-app as a library dependency and running npm install
it tries to exectute "postinstall": "./scripts/postinstall.sh".

This doesn't work in in windows 10 64 bit

**Environment**
Develop (latest)

**Comment by dhrn** [comment]
use git bash

**Comment by DenysVuika** [comment]
Most of the node.js community is using git bash when dealing with node and derived tooling. Windows command prompt and Powershell are known to have many problems.

**Comment by DenysVuika** [comment]
I am closing this for now as all ADF and ADF-apps infrastructure we have is base on .sh scripts and I am not sure we are going to build 2 configurations right now.

**Comment by DenysVuika** [comment]
The postinstall script does not affect the application, you can still start it. The workaround is to remove the "postinstall" script from the "package.json". 
We will try to address this issue in the next release.

**Comment by DenysVuika** [comment]
Fixed
