### ISSUE TITLE
User profile information in an evaluator is empty on first load when navigation is the libraries view

### ISSUE THREAD

**Issue by dylanvdbrink** [Alfresco/alfresco-content-app#1493]
**Describe the bug**
I've created the following evaluator to check for the groups of the current user. 
```javascript
function hasGroups(context: RuleContext, ...groups: Array<String>) {
    console.log(context.profile);
    if (!context.profile || !context.profile.groups) {
        console.log('return false, context profile is null %o', context.profile);
        return false;
    }

    let userGroups = context.profile.groups;
    if (userGroups.length < 1) {
        return false;
    }

    let userGroupsIds = userGroups.map(userGroup => userGroup.id);
    return groups.every(group => userGroupsIds.includes(group.toString()));
}
```

This evaluator is used within the "create menu":
```
"rules": [
    {
        "id": "client-extensions.rules.canCreateSite",
        "type": "client-extensions.evaluators.hasGroups",
        "parameters": [ "GROUP_SITE_CREATORS" ]
    }
],
...
"features": {
    "create": [
        {
                "id": "client-extensions.create.projectsite",
                "type": "default",
                "icon": "create_new_folder",
                "order": 610,
                "title": "CLIENT.NEW_MENU.MENU_ITEMS.CREATEPROJECTSITE",
                "actions": {
                    "click": "client-extensions.actions.createprojectsite"
                },
                "rules": {
                    "visible": "client-extensions.rules.canCreateSite"
                }
            }
    ]
}
```

This works when the active navigation is a folder (url `/libraries/FOLDER_NODEREF`). But when I reload the app to the libraries/sites view (url `/libraries`) the `context.profile` object has all empty/null values and the `groups` property of `profile` is `undefined`.

**Environment**
- ACA version: 1.10.1
- ACS version: 5.2, 6.0
- ADW version: 1.4.1

**To Reproduce**
1. Declare the evaluator above and use it within the `extension.plugin.json`
2. Login as a user which is in the `GROUP_SITE_CREATORS` group
3. Go to the libraries view (`/libraries`)
4. Button in the create menu is not visible and console shows the logs because `context.profile.groups` is falsy.
<img width="542" alt="image" src="https://user-images.githubusercontent.com/4668186/85122520-f9f05500-b226-11ea-93e7-f6aa35629044.png">

Logs
<img width="505" alt="image" src="https://user-images.githubusercontent.com/4668186/85122668-39b73c80-b227-11ea-8948-53a02d939a41.png">
5. Click on a library in the documentList
6. Button in the create menu is visible
<img width="584" alt="image" src="https://user-images.githubusercontent.com/4668186/85122542-01176300-b227-11ea-9c0a-28730804aa34.png">

Logs
<img width="317" alt="image" src="https://user-images.githubusercontent.com/4668186/85122834-7daa4180-b227-11ea-82dd-7c06c7fb8d4a.png">
7. Click on "Libraries" in the sidebar
8. Button in the create menu is still visible
<img width="560" alt="image" src="https://user-images.githubusercontent.com/4668186/85122552-05438080-b227-11ea-88f9-51707dea1e66.png">

Logs
<img width="335" alt="image" src="https://user-images.githubusercontent.com/4668186/85123323-5bfd8a00-b228-11ea-8fdb-0b2ec5c6f7c0.png">

**Expected behavior**
1. Declare the evaluator above and use it within the `extension.plugin.json`
2. Login as a user which is in the `GROUP_SITE_CREATORS` group
3. Go to the libraries view (`/libraries`)
4. Button in the create menu is visible

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Comment by inavarre** [comment]
Hi @dylanvdbrink  thank you for raising this bug. We have raised it internally here - https://issues.alfresco.com/jira/browse/ACA-3730

Apologies for the slow reply on here. As a partner using ADW, you are able to report these bugs via the support portal here - http://support.alfresco.com/

**Comment by dylanvdbrink** [comment]
@inavarre Thanks! I will track that one then.

**Comment by arditdomi** [comment]
Hi @dylanvdbrink thank you for reporting this. The issue has been fixed and you should be able to use it in the next release.

**Comment by dylanvdbrink** [comment]
@arditdomi No problem. I've seen the recent changelog, thank you for the update!
