### ISSUE TITLE
Search Tools

### ISSUE THREAD

**Issue by marcogianini** [Alfresco/alfresco-content-app#1497]
Good night Community,
I am very new to ACA and I have problems with a basic tool inside Alfresco.

Using the yo alfresco-adf-app by default, when I start npm start and successfully log, I notice that the "Search" magnifier does not appear on the home screen.

Does anyone know how to inform me how can I put this tool?

My environment is:
Ubuntu 20.04
Version A.C.A (via yo alfresco-adf-app --version) - 3.1.0
Alfresco Docker 6.2 Community
Node v12.13.0
npm v.6.13.0
Angular CLI v.7.3.9
Yomman v3.1.0

**Comment by DenysVuika** [comment]
Yeoman template for content application is not related to this project. The yeoman template gives you the pure basic app with JavaScript api preconfigured, and some basic content related components. Stuff like search is something you need to add yourself.

This repository is about fully functional application. Please see the documentation link and the readme.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by marcogianini** [comment]
Thanks for all.
