### ISSUE TITLE
Angular 9 compatibility

### ISSUE THREAD

**Issue by corentinguilloux** [Alfresco/alfresco-content-app#1529]
**Using ADF into an existing Angular 9 project**
I would like to use ADF into an existing Angular project. The problem is that my project uses Angular 9 and I have compatibility problems when I want to use ADF into it. 
I know that ADF is only Angular 7 compatible for the moment, is it possible to increase the Angular version compatibility ?

**Comment by DenysVuika** [comment]
We are working on the Angular 10 upgrade for ADF and all the apps. So the next release of ACA will be based on Angular 10

**Comment by DenysVuika** [comment]
The`develop` branch (default one you see on GitHub) is already Angular 10, but still not released. You can check and see if you have any issues to report, thanks.

**Comment by corentinguilloux** [comment]
Okay thanks, i'll check it 👍
