### ISSUE TITLE
Need better zero state for login page when repo has not started

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-content-app#162]
I'm working on a blog post about getting this app up and running very quickly (adding the `gui81/alfresco` docker image to the docker-compose.yaml file and updating the nginx config to do the reverse proxying.) What I have noticed is this apps obviously starts way faster than the repo. If I navigate to this app it loads with a a blank page. Once the repo starts I get a basic auth login dialog. If I cancel that, the page loads properly. Would be great if there was some sort of progress/zero-state that indicated that we were attempting to reach out to the servers...

**Comment by john-knowles** [comment]
The application has some other empty states, when there is no content to display and there is a story in the backlog to cover this: https://issues.alfresco.com/jira/browse/ACA-9

**Comment by DenisVuyka** [comment]
We cannot do much about all possible multi-container solutions developers may setup. 

Not sure the Login dialog should have any responsibility for ACS container warming up or startup, and even for assuming it's in the docker, and not part of the local ready-to-use setup. 

There are tools like https://github.com/jeffbski/wait-on that might help docker develpers start the webapp part/container based on the conditions and checks for another one. So I suggest closing this ticket for now and reopening later if needed.

**Comment by binduwavell** [comment]
The issue here is not docker. The issue is that app startup experience is bad when the repo is not running (for whatever reason.)

**Comment by DenisVuyka** [comment]
The app is blank when you use development server because it compiles longer. Angular CLI just starts the browser early. This is not the case for the published apps and those served from the server
