### ISSUE TITLE
Right-To-Left Document List Layout has a blank right margin

### ISSUE THREAD

**Issue by jamilnour** [Alfresco/alfresco-content-app#1639]
**Describe the bug**
After switching to RTL a blank rectangle is shown in the right

**Environment**
- ACS version: [e.g. 6.2]

**To Reproduce**
1. Add locale:"ar" to app.config.json
2. Run ACA and login
3. The margin will be clearly shown as per the attachment

**Expected behavior**
I remember it was working perfect in version 1.9 with no margin

**Screenshots**
Attached "RTL-with-margin-issue.png"

**Desktop (please complete the following information):**
 - OS: Windows and Linux
 - All Browsers
 
![RTL-with-margin-issue](https://user-images.githubusercontent.com/3115232/91373509-8ea59f00-e7e4-11ea-9bd5-968ae1bddf21.png)

**Smartphone (Works fine because the side navigation is on the top of the document list.):
 - Device:  Not applied
 - OS: iOS and Android
 - Browser: All

**Additional context**

**Comment by eromano** [comment]
Not able to replicate in the last version please update and reopen if necessary
