### ISSUE TITLE
Issue with sharing preview links to users that are not already logged in

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-content-app#164]
I navigate to a preview page (http://localhost:3000/#/preview/99cb2789-f67e-41ff-bea9-505c138a6b23).
I copy the link.
I log out of the application.
I paste the link.
I am prompted with a basic auth dialog (yuck).
I cancel this dialog and am prompted with the login page.

Expected result:
I see the preview I pasted the link for

Actual result:
I am taken to: http://localhost:3000/#/personal-files/99cb2789-f67e-41ff-bea9-505c138a6b23 which is a very strange page that looks like this:

![image](https://user-images.githubusercontent.com/115754/34082673-dc9dfcc4-e31f-11e7-8267-f52001933309.png)

**Comment by john-knowles** [comment]
Thank you - I have raised a bug in the JIRA backlog for this https://issues.alfresco.com/jira/browse/ACA-1066.

Side note, the basic auth dialog that pops up is resolved in the platform; expect to see that fix in v5.2.3.

**Comment by binduwavell** [comment]
FYI, I don’t have access to the JIRA. Any chance that can be changed given this is All open source? Does not support collaboration if non-team members can’t have a full sense of the backlog.

**Comment by john-knowles** [comment]
That URL should work now.

**Comment by binduwavell** [comment]
Thanks John!
