### ISSUE TITLE
facet search filter does not reset on new search

### ISSUE THREAD

**Issue by archX-S** [Alfresco/alfresco-content-app#1690]
**Describe the bug**
facet search filter does not reset on new search. 

**Environment**
- ACA version: 2.0.1
- ACS version: 6.2

**To Reproduce**
1. Open the ACA
2. Login
3. Click on search field
4. enter a word and confirm
5. use facet filter like File type "pdf".
6. Click on libraries
7. Click on search field
8. enter an other word and confirm

the facet filter is still active but not displayed correct. 

**Expected behavior**
The filters must be reset for a new search 

or 

- All filters with all options must be displayed correct.
- adf-search-filter does not show all options and the selected are not checked. 
- adf-search-chip-list does not show the selected.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux / Ubuntu / Windows
 - Browser chnrome
 - Version 85
**Smartphone (please complete the following information):**

**Comment by eromano** [comment]
Solved in 2.4.0
