### ISSUE TITLE
Preview thumbnail pdf fail when i modify  the target context path of the alfresco api

### ISSUE THREAD

**Issue by p4535992** [Alfresco/alfresco-content-app#1694]
**Describe the bug**

After modify the file 'proxy.conf.js' with this configuration

```typescript
const API_CONTENT_HOST = "http://myip:8080/gateway"; //process.env.API_CONTENT_HOST || 'http://0.0.0.0:8080';

module.exports = {
  '/alfresco': {
    target: API_CONTENT_HOST,
    secure: false,
    changeOrigin: false,  //TESTED WITH BOTH true and false
    // workaround for REPO-2260
    onProxyRes: function(proxyRes, req, res) {
      const header = proxyRes.headers['www-authenticate'];
      if (header && header.startsWith('Basic')) {
        proxyRes.headers['www-authenticate'] = 'x' + header;
      }
    }
  },
  // '/auth': {
  //   target: "http://192.168.1.153:8080/gateway/api/proxy",//API_CONTENT_HOST,
  //   secure: false,
  //   changeOrigin: true
  // }
};
```

The document list work fine, but when i double click on a document the preview pdf fail and tell me the error 403 . 

Here a example of the url:

http://localhost:4200/alfresco/api/-default-/public/alfresco/versions/1/nodes/fde117a7-ce39-41d6-99f0-6addc36a07e0/renditions/pdf/content?attachment=false&alf_ticket=TICKET_b190eb2b0839b233235d2bb632be7f194d075c68

Here what i get from the browser:

Request URL: http://localhost:4200/alfresco/api/-default-/public/alfresco/versions/1/nodes/fde117a7-ce39-41d6-99f0-6addc36a07e0/renditions/pdf/content?attachment=false&alf_ticket=TICKET_b190eb2b0839b233235d2bb632be7f194d075c68
Request Method: GET
Status Code: 403 Forbidden
Remote Address: 127.0.0.1:4200
Referrer Policy: no-referrer-when-downgrade

**Environment**

- ACA version: 1.11.0
- ACS version: 6.2
- ADF version: 4.0.0

NOTE: i don't get the last release i just clone the current state of  the project for some test

**To Reproduce**
1. Change the configuration on the file  'proxy.conf.js'  with a custom path target for the alfresco api context (see the bug description for the code)
2. Check out the document list
3. Double Click on a document
4. The angular component 'adf-pdf-viewer' is loaded, but i can't see the preview of the document
4. Error is displayed on the web console of the browser Request URL with status code 403

**Expected behavior**

After double click on a document i excepted to see a preview of the content.

**Desktop (please complete the following information):**

 - OS: Client ADF on WIndows [Windows 10]] , Server Alfresco on Linux (Centos 7]
 - Browser Chrome
 - Version 85.0.4183.121

**Additional context**

Just started to study ADF component but, it's seem the component "adf-pdf-viewer" it' using a worng url? The current attribute is  ```ng-reflect-url-file="http://localhost:4200/alfresco"``` and it should be  ```ng-reflect-url-file="http://myip:8080/gateway/alfresco" ```?

**Comment by p4535992** [comment]
The problem persist on version 4.1.0 of ADF components the preview still call the url:

```
http://localhost:4200/alfresco/api/-default-/public/alfresco/versions/1/nodes/46bd53d1-667f-4546-aa5e-61f8411a7080/renditions/pdf/content?attachment=false&alf_ticket=TICKET_07d4a70add17d995348ed2c17dce46f1cacea3a9
``
instead of

```
http://myip:8080/gateway/alfresco/api/-default-/public/alfresco/versions/1/nodes/46bd53d1-667f-4546-aa5e-61f8411a7080/renditions/pdf/content?attachment=false&alf_ticket=TICKET_07d4a70add17d995348ed2c17dce46f1cacea3a9
```

Anyone can suggest a workaround ?

**Comment by p4535992** [comment]
The problem persist on version 4.1.0 of ADF components the preview still call the url:

On client:
```
http://localhost:4200/alfresco/api/-default-/public/alfresco/versions/1/nodes/46bd53d1-667f-4546-aa5e-61f8411a7080/renditions/pdf/content?attachment=false&alf_ticket=TICKET_07d4a70add17d995348ed2c17dce46f1cacea3a9
```
On server:
```
http://myip:8080/alfresco/api/-default-/public/alfresco/versions/1/nodes/46bd53d1-667f-4546-aa5e-61f8411a7080/renditions/pdf/content?attachment=false&alf_ticket=TICKET_07d4a70add17d995348ed2c17dce46f1cacea3a9
```
instead of

On Server:

```
http://myip:8080/gateway/alfresco/api/-default-/public/alfresco/versions/1/nodes/46bd53d1-667f-4546-aa5e-61f8411a7080/renditions/pdf/content?attachment=false&alf_ticket=TICKET_07d4a70add17d995348ed2c17dce46f1cacea3a9
```
Anyone can suggest a workaround ?

**Comment by DenysVuika** [comment]
Your custom URL may be a problem, as you get "403 Forbidden", probably incorrect authentication, or something else. It's hard to say just having your custom url example. Check your server, check CORS, etc.

**Comment by p4535992** [comment]
For anyone have this problem, for me was the fact the call for the node content doesn't set the header "Content-Type" equals to "application/json"  for unknown reason, so here my two solution:

1) if you have control on the server disable the check for the header "Content-Type" on the controller
2) if you have control on the client make sure the header "Content-Type" is equals to "application/json" on the request get
