### ISSUE TITLE
Repository sometimes fails to start when docker-compose.yml file is to deploy.

### ISSUE THREAD

**Issue by alf-wchong** [Alfresco/alfresco-content-app#1703]
**Describe the bug**
Repository container sometimes fails to start when docker-compose.yml file is used for deployment.

**Environment**
- ACS version: latest

**To Reproduce**
1. Deploy with docker-compose.
2. Check state of repository docker container with docker ps -a
3. Note that alfresco-content-app_alfresco_1 has exited

**Expected behavior**
Repository container starts and remains running.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Irrelevant

**Smartphone (please complete the following information):**
Irrelevant

**Resolution**
A race condition exists with the startup of the database container. This is resolved with the addition of a dependency on the database in the definition for the repository.
`services:`
`  alfresco:`
`    image: alfresco/alfresco-content-repository:latest`
`    mem_limit: 1000m`
`    depends_on:`
`      - auth`
`      **- postgres**`
`...`

**Comment by DenysVuika** [comment]
This is not an ACS repository, but ACA. This project focuses on the client-side application.
