### ISSUE TITLE
Check settings before publishing to Docker

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-content-app#172]
Check the following environment variables prior to publishing to Docker:

- DOCKER_REPO
- DOCKER_USERNAME
- DOCKER_PASSWORD

This should prevent issues when external developers fork the project and don't want Docker integration automatically enabled and failing.

**Comment by binduwavell** [comment]
Noice

**Comment by DenisVuyka** [comment]
Closing this issue as we are removing publishing step from the Travis CI.
