### ISSUE TITLE
Update with features from ngrx

### ISSUE THREAD

**Issue by dhanushkac** [Alfresco/alfresco-content-app#1763]
I have noticed that this project is continuously updating. When I am going through the code I found that the actions and reducers are written in the old way without using `createAction`, `createReducer` and `on` from `@ngrx/store`. Any reason not to update? are there any issues of moving to those? 
Thank you.

**Comment by DenysVuika** [comment]
No particular reason or blocker, we just have not yet upgraded ngrx as it's quite a big change.

**Comment by dhanushkac** [comment]
> No particular reason or blocker, we just have not yet upgraded ngrx as it's quite a big change.

Thank you for your reply. When you do buzz me as well. I would love to contribute.

**Comment by DenysVuika** [comment]
There's nobody working on this upgrade right now, so you can contribute the PR if you are familiar with ngrx. thanks!

**Comment by DenysVuika** [comment]
Closing as it should be using the latest ngrx so far
