### ISSUE TITLE
Resel all button on Filter do no reset categories like for example size 

### ISSUE THREAD

**Issue by n-rodrig** [Alfresco/alfresco-content-app#1768]
**Describe the bug**
When pressing _reset All_ button most of fields are cleared but no those defined as the categories on app.config.json for example size.

**Environment**
- ACA version: [e.g. 2.0.1]
- ACS version: [e.g. 6.2]

**To Reproduce**
1. Open the ACA
2. Login
3. Click on search field
4. enter a word and confirm
5. click on size filter and select some check
6. Click on Reset all button

**Expected behavior**
Filter Size checks should be cleared when pressing reset all

**Screenshots**
![imagen](https://user-images.githubusercontent.com/12884810/98063835-daaa3b00-1e48-11eb-962d-8f09949c12a2.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20
 - Browser Firefox 
 - Version 82.0

**Comment by eromano** [comment]
https://alfresco.atlassian.net/browse/MNT-22207

**Comment by eromano** [comment]
Solved in 2.4.0
