### ISSUE TITLE
Icon displacement on using invalid material icons

### ISSUE THREAD

**Issue by Abbaskarara52** [Alfresco/alfresco-content-app#1866]
**Describe the bug**
On Extending the "New" option from app.extension.json file, the icon moves to the center of the option (see the file attached) if an invalid icon name is provided
Issue appears only if invalid icon name is provided, i.e. replacing "file_add" with "add" works. Ideally, no icon should appear.

**Environment**
- ACA version: [e.g. 1.6]
- ACS version: 6.2

**To Reproduce**
1. Go to _app.extensions.json_
2. in the features > create add the below snippet on top of the json Array
{
        "id": "app.create.createCutom",
        "order": 10,
        "icon": "file_add",
        "title": "Custom File Upload",
        "description": "Custom File Upload",
        "description-disabled": "Custom File Upload No Allowed",
        "actions": {
          "click": "UPLOAD_FILES"
        },
        "rules": {
          "enabled": "app.navigation.folder.canUpload"
        }
      },
2. Start the server, and click on **New** after login

**Expected behavior**
All Valid Icons defined must be aligned to left of the text in the dropdown option 
Invalid icons should not appear at all.

**Screenshots**
ACA-issue.jpg: shows the issue
ACA-working.jpg: shows the fix on replacing icon with already provided
![ACA-working](https://user-images.githubusercontent.com/9657298/101453052-bb756080-3954-11eb-8bc0-368014f20cf3.JPG)
![ACA-issue](https://user-images.githubusercontent.com/9657298/101453054-bc0df700-3954-11eb-8fcd-ab63474140fc.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 22

**Comment by DenysVuika** [comment]
If it's a material icon, we don't control the key of the icon, just pass it to the "mat-icon" component. I think it's your responsibility to verify the test that all icons are valid. Maintaining a list of google icons and comparing with what developers may incorrectly type might be an overhead

**Comment by Abbaskarara52** [comment]
@DenysVuika  thank you for your response. 
just for reference, the icons can be picked from part of string if an exact match is not found e.g. "file_add" would render an "add" icon, hence the issue with UI will appear as stated in the bug. not sure if the issue is with mat-icon itself
