### ISSUE TITLE
How to include and activate Process Services

### ISSUE THREAD

**Issue by Tonne-TM** [Alfresco/alfresco-content-app#2192]
### Problem
We do not know how to add Process Services to the Content App. They are [included in the Digital Workspace](https://docs.alfresco.com/digital-workspace/latest/process/config/), but as we need to make some adjustments to the Digital Workspace we are forced to use the Content App.
(The described way in the following Hub post is not working: https://hub.alfresco.com/t5/application-development/adding-processes-to-the-content-app/td-p/293718)

### Possible Solution
Add a documentation on how to add Process Services to the Content App.

### Alternative Solution
Add Process Services by default, as in the Digital Workspace.

**Comment by mauriziovitale** [comment]
Hi @Tonne-TM what is not clear to me is if you have Alfresco Digital Workspace (Enterprise App) or not. If you have ADW  you need  Alfresco Process Services (back end) and at this point, you can switch the processService property to true. Although ADW is built on top of ACA, enabling Process Service from ACA is not so straightforward.

**Comment by Tonne-TM** [comment]
We are using ACA and want to add Process Service to ist (we have all the needed process service backend running).

> enabling Process Service from ACA is not so straightforward.
Is there a documentation for it? Since in the forum post I linked in the ticket there was an explanation on how to add it, but it is not working anymore.

**Comment by dhrn** [comment]
Hello @Tonne-TM 
We have docs for [how to extend ACA](https://alfresco-content-app.netlify.app/#/). Here is one of the implementations https://github.com/atolcd/adf-onlyoffice-extension.

here I am listing what you have to do 

* create an extension library for the process service
* Add your layouts/routes/menus/etc to the above library

I suggest you read the docs first.  we do have [example angular application](https://github.com/Alfresco/alfresco-ng2-components/tree/develop/demo-shell) for testing purposes. 

I hope this helps. Start hacking :slightly_smiling_face:

**Comment by mauriziovitale** [comment]
Thanks, @dhrn. I will close the ticket.
