### ISSUE TITLE
Move PageComponent and related services to ACA shared library

### ISSUE THREAD

**Issue by rderooij** [Alfresco/alfresco-content-app#2235]
**Is your feature request related to a problem? Please describe.**

We are using the extension’s framework of ACA which works very well. Some of the functionality (PageComponent, ContentManagementService, NodeActionsService, NodeTemplateService) we use are in the source code of the content app and is not available from a library perspective. When adding these dependencies in your library you will get circular dependency issues. NodeActionsService triggers also dialogs which are also located in source code of the content app (NodeVersions and NodeTemplate). 

**Describe the solution you'd like**

We have to copy these services in our ‘shared’ services to be used when developing custom libraries for the content app. 
Our suggestion is to move the PageComponent and related services to aca-shared library in order to import these services in our own libraries.

**Comment by DenysVuika** [comment]
Most of the ACA functionality is now a library, so closing as done
