### ISSUE TITLE
I cant' open alfresco content application

### ISSUE THREAD

**Issue by Bers12** [Alfresco/alfresco-content-app#2236]
Hello!I installed alfresco using ansble method of installation from this site
https://docs.alfresco.com/content-services/community/install/ansible/

 When i open it  in browser-there is no alfresco content application.
There is a blank window.But there should be identification window to alfresco content application.
I can enter alfresco using this link 192.168.1.161/share.But i also need alfresco content application.

![alfa](https://user-images.githubusercontent.com/87566544/126033565-5b88f8ac-0f8e-4627-95c5-48bbc7761d27.jpg)

**Comment by DenysVuika** [comment]
ACA is an open source application that you can get, build and install yourself with the ACS. It's not coming with the installer as far as I know.
