### ISSUE TITLE
Alfresco API Resources missing when navigating 

### ISSUE THREAD

**Issue by angelborroy-ks** [Alfresco/alfresco-content-app#227]
zone.js:2935 

GET http://localhost:3000/alfresco/api/-default-/public/alfresco/versions/1/people/-me-/favorites/ed3df4d2-66ee-4728-8b1f-d72c155c8fb1 404 (Not Found)

Using Alfresco 201707 as backend

**Comment by DenisVuyka** [comment]
There should be some console activity due to the way we detect "is favorite" state. We handle the 404 as the "not present" status due to some ACS api limitations. Should be fixed with ACS v6 I believe. Can you please confirm if the list is still working for you regardless of the browser console?

**Comment by angelborroy-ks** [comment]
Everything seems to work fine. 

But there are some folders from a customised type that can't be opened. I'm investigating further to identify where the problem is. But it looks like it's not related with this one.

**Comment by john-knowles** [comment]
@angelborroy-ks did you get anywhere with the investigation or shall we close this ticket now?

**Comment by angelborroy-ks** [comment]
Sorry @john-knowles, I missed that.

I'm closing this issue as it was not related with any other problems.

Thanks
