### ISSUE TITLE
Alfresco JIRA Links no longer work

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-content-app#2312]
**Describe the bug**
JIRA links mentioned in the GitHub issue tracker no longer seems to work.

**Environment**
- ACA version: [e.g. 1.6]
- ACS version: [e.g. 6.1]

**To Reproduce**
Try to access any JIRA link mentioned in the issue tracker on GitHub.

**Expected behavior**
The link should work.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrea-ligios** [comment]
I've checked and _Autolink references_ are correct, eg: ACA-1918

Those old issues have just wrong links hardcoded.

**Comment by dhrn** [comment]
@bhagyas Thank you for reporting. It seems fixed now. please re open if required
