### ISSUE TITLE
Release tags on docker hub

### ISSUE THREAD

**Issue by federicotarantino** [Alfresco/alfresco-content-app#2336]
Hi,
I am seeing on docker hub last published tag is 2.3.0.
Have you blocked releases on docker hub?

https://hub.docker.com/r/alfresco/alfresco-content-app/tags

**Comment by DenysVuika** [comment]
Might have been some issues with deployment, I can see 2.7.0 there already.

**Comment by federicotarantino** [comment]
Perfect! Thanks
