### ISSUE TITLE
I upload a chinese md file, It seems to be garbled,It  is unable to display Chinese normally

### ISSUE THREAD

**Issue by qiaofeng1227** [Alfresco/alfresco-content-app#2393]
![image](https://user-images.githubusercontent.com/43192516/148875532-3ba1577f-339e-411c-a42d-e8e8a42ff94f.png)

**Comment by qiaofeng1227** [comment]
It's great when you can support MD files

**Comment by DenysVuika** [comment]
Closing as this screenshot is about Share, not ACA codebase. Please reopen or provide more details if it is related to ACA
