### ISSUE TITLE
Different languages mess up button texts

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-content-app#2426]
**Describe the bug**
In some translations for example in German, the text in some buttons will look messed up:

![image](https://user-images.githubusercontent.com/43036408/152530676-45bb078c-9b37-4b22-8e95-6920f69aa340.png)

**Environment**
- ACA version: 2.8.0
- 
**To Reproduce**
1. Login
2. Change Language to "German"
3. Go into the details view

**Expected behavior**
Text and Button should adjust based on length and not be messing up the view.

**Desktop (please complete the following information):**
- Chrome (latest stable)

**Comment by DenysVuika** [comment]
Should be addressed by the coming Properties UI/UX
