### ISSUE TITLE
Expose login component setting in app.config

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-content-app#2548]
Have been discussing this with Denys. 

The login component has a bunch of configuration https://github.com/Alfresco/alfresco-ng2-components/blob/develop/docs/core/components/login.component.md#custom-logo-and-background

In ACA these values are hard coded and can't be set in app.config.

We would like these settings to be configurable in ADW:

- backgroundImageUrl
- logoImageUrl

These look like they would also be helpful:

- needHelpLink
- registerLink
- showRememberMe

**Comment by DenysVuika** [comment]
should be covered by the `landingPage` attribute in the `app.config.json`
