### ISSUE TITLE
Setting headerTextColor in app.config does not affect the UserInfo component

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-content-app#2552]
**Describe the bug**

Try setting a dark header color in app.config (headerColor = #303f9f) the default header text (which is black) is challenging to see. So set the headerTextColor to white #ffffff. The menu icon, the text, etc all go white except the UserInfo component, which continues to have black text. We would like all header components rendered on the header color to be affected by headerTextColor. Note that since the search box has black text on a white background, no changes are needed there.

**Environment**
- ACA version: 2.8.0
- ACS version: 7.2.0

**Expected behavior**
Text color applied to header is applied to all components on the header.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 101.0.1

**Comment by DenysVuika** [comment]
closing as the header component has been deprecated in favor of new improved layout
