### ISSUE TITLE
Improve situation around required node version when developing for ACA/ADW.

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-content-app#2556]
Since both ACA an ADW require an older version of Node, and ideally a specific version range (~14) it would be good to add this information to the documentation and for those of us who make use of the Node Version Manager, if you add a .nvmrc to the root of each of these projects folks can `nvm install` and `nvm use` in the project root and get the right version.

The following trick for folks using zsh allows for the nvm to be done automatically: https://github.com/nvm-sh/nvm#zsh

**Comment by DenysVuika** [comment]
added support for `.nvmrc`, we already have tasks to support Node 18 in the coming releases
