### ISSUE TITLE
SET_HEADER_COLOR does not work - fix proposed

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-content-app#2563]
**Describe the bug**
Attempt to use `SET_HEADER_COLOR` in `extension.json` does not work.

**Environment**
- ACA version: 2.11.0
- ADW version: 2.9.0
- ACS version: 7.2

**Additional context**
The argument here: https://github.com/Alfresco/alfresco-content-app/blob/b7ba7b94b246e79ce75043c1ad825e233f3b847f/projects/aca-shared/store/src/actions/app.actions.ts#L67 should be called payload and not color.

In the same way the `.color` at the end of https://github.com/Alfresco/alfresco-content-app/blob/23262d094917841583e9440a3800cd405b104e8a/app/src/app/store/reducers/app.reducer.ts#L56 should be changed to `.payload`.

**Comment by DenysVuika** [comment]
closing as header component was reworked with ACA 4.0.0
