### ISSUE TITLE
Update peer deps

### ISSUE THREAD

**Issue by nickyhaze-incentro** [Alfresco/alfresco-content-app#2618]
Hi, shouldn't the peer deps be updated according the new Angular version/release within ADF?

https://github.com/Alfresco/alfresco-content-app/blob/8312bf8d849b3f75a52f6ec019156788db5bbbf0/projects/adf-office-services-ext/package.json#L16

**Comment by DenysVuika** [comment]
No longer relevant as the `package.json` files were removed from the extension projects
