### ISSUE TITLE
wrong AOS URL generated

### ISSUE THREAD

**Issue by romainbrochot** [Alfresco/alfresco-content-app#2625]
**Describe the bug**
AOS URL generated in adf-office-services-ext extension seems to be wrong.

**Environment**
- ACA version: 2.2.0+
- ACS version: 6.2+

**To Reproduce**
1. Go to a docx node in a library/site
2. Right click and choose "Edit in Microsoft Office TM"
3. Microsoft Word opens and says Unable to connect to : https://server.domain/alfresco/aos/Sites/_aos_nodeid/XXXX-XXXX-XXXX/document.docx where XXXX-XXXX-XXXX is the document uuid.
4. Changing the URL to https://server.domain/alfresco/aos/_aos_nodeid/XXXX-XXXX-XXXX/document.docx and manually testing it in a browser works. We also try adding the full path eg: /alfresco/aos/Sites/thesiteshortname/documentLibrary/ in vain.

**Expected behavior**
Clicking the action should generate proper AOS url.
The "root" variable in the service seems to be the culprit, only taking the second element of the path array.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version : latest

**Additional context**

**Comment by jeremie-lesage** [comment]
We also have this bug, but this is a Share issue.

I found the commit that introduced the regression

https://github.com/Alfresco/alfresco-community-share/commit/e950cd344fc384b06b9dc7903918a4be8c5a0a8d

We use Office 2010, we think there is no problem with more recent versions of MS Office.

The last docker version, that works with Office 2010 is `alfresco/alfresco-share:6.1.0`

**Comment by romainbrochot** [comment]
@jeremie-lesage Not sure how Share could impact ADF or ACA ;)
in the end, we used this code https://github.com/keensoft/ng2-alfresco-aos-editonline that takes care of the 256 char limit
