### ISSUE TITLE
Please update the compatibility matrix in docs/README.md

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-content-app#2642]
The file goes up to ACA 2.4, clearly 3.0 does not work with ACS 7.2 (folder rules stuff not working.) It would be great to get this list updated.

Many thanks!

**Comment by DenysVuika** [comment]
We will update the matrix for the upcoming release, thanks for the reminder. To answer the question: The v1 folder rules is a new feature in ACS 7.3, although it will be released as part of the private API until 7.4
