### ISSUE TITLE
General responsiveness / Mobile first

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-content-app#2790]
**Describe the bug**
In a lot of places, there is no responsiveness. Currently the application can't be fully used on many mobile devices. Maybe there needs to be a switch to a mobile first approach. We get the feedback from a lot of customers having smaller screens, oder trying to access the application on mobile devices. 

**Environment**
- ACA version: 3.1.0

**Expected behavior**
Full responsiveness, with being able to use all features of the application on mobile devices, no matter which language is chosen in the settings.

**Comment by DenysVuika** [comment]
it's impossible to address this issue without specifics. What are the places, which components, what is the expected behaviour, what is actual behaviour, etc. Closing for now and recommend opening issues with specific details
