### ISSUE TITLE
How to build project with .env config

### ISSUE THREAD

**Issue by hnpanther** [Alfresco/alfresco-content-app#2958]
Hi
I want to build content-ce project. My alfresco repository runs on another server and different port. I set it's url in config file(.env) and when use npm start everything is ok but when build project using ng build content-ce and copy dist folder to nginx,.env file don't applied. How to build project with custom url of alfresco repository in .env file?

**Comment by DenysVuika** [comment]
The .env files are only for local development, for the final deployment, you need to update the app.config.json file.

**Comment by hnpanther** [comment]
> The .env files are only for local development, for the final deployment, you need to update the app.config.json file.

thank you very much
