### ISSUE TITLE
Side navigation menu toggling error

### ISSUE THREAD

**Issue by howkymike** [Alfresco/alfresco-content-app#2962]
**Describe the bug**
Side navigation bar button (responsible for toggling side navbar) does not work with the new routes in the custom projects.

**Environment**
- ACA version: 4.0.0-A.2
- ACS version: 7.2.0

**To Reproduce**
1. Create a new extension (i.e. following https://hub.alfresco.com/t5/application-development/developing-take-ownership-extension-for-aca-2-8-0/ba-p/311606) 
2. Go to the newly created page
3. Click menu button in the top left corner. 
4. Side navigation bar will not toggle, an error will appear
```
core.mjs:7640 ERROR TypeError: Cannot read properties of undefined (reading 'toggleMenu')
    at AppHeaderComponent.onToggleSidenav (header.component.ts:91:22)
    at AppHeaderComponent_Template_adf_layout_header_clicked_0_listener (header.component.html:7:14)
    ...
```

**Expected behavior**
The side navigation should toggle on the button click.

**Additional context**
In the aca-content project there is no problem, because components are rendered using the app-shell, they see to be dynamically injected. However, when using static routes and the default "app-layout" layout, the "data" Input (which contains the layout property) is passed empty to the AppHeaderComponent.
To fix it, I propose to add in the *app-layout-component.html* file in the <app-header> element the following code:
```
[data]="{layout: layout, isMenuMinimized: isMenuMinimized()}"
```

**Comment by DenysVuika** [comment]
I presume you were using the alpha versions. with the release this component was moved to ADF, and toggle button should be working fine.
