### ISSUE TITLE
Dockerfile 

### ISSUE THREAD

**Issue by shahadrn** [Alfresco/alfresco-content-app#3096]
In Dockerfile Why did they delete these commands?

# RUN mkdir -p ./licenses && \
#   yarn licenses list --production > ./licenses/licenses.txt && \
#   yarn licenses generate-disclaimer --production > ./licenses/disclaimer.txt

**Comment by DenysVuika** [comment]
the commands were breaking with the docker due to unknown reasons, we temporarily removed that while working on a better solution. you can add those to your custom Dockerfile if that gives you troubles. Note: the Dockerfile you get with ACA is an example only.
