### ISSUE TITLE
Invisible "More settings" icon on mobile

### ISSUE THREAD

**Issue by howkymike** [Alfresco/alfresco-content-app#3108]
**Describe the bug**
The "More settings" icon (3 dots) in the header in the mobile is not visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/34208123/230423855-d0539323-2ca5-4479-9fe5-4cdf5bc7ed06.png)

**Environment**
- ACA version: 4.0.0-A.3

**Additional context**
It is shown but outside of the view. I propse to merge User icon with More Settings.

**Comment by DenysVuika** [comment]
With 4.0.0 the ACA is featuring the new layout, please check if that works for you. 

Here's the iPad emulation view: 
<img width="856" alt="Screenshot 2023-05-06 at 16 24 13" src="https://user-images.githubusercontent.com/503991/236633080-39ff3e73-2e77-4825-9751-3f73a73dda1b.png">
