### ISSUE TITLE
Docker deployment page cannot load

### ISSUE THREAD

**Issue by huyubao** [Alfresco/alfresco-content-app#3209]
**Describe the bug**
We used the Docker script that comes with the development branch to run, but the page cannot be loaded after deployment is completed

**To Reproduce**
1. Run  sh ./docker/build.sh
2.  sh ./docker/run-content-ce.sh
3. Waiting for script execution to complete
4. open http://localhost:8081/

**Expected behavior**
The same effect as executing npm start -- configuration=adf

**Screenshots**
![image](https://github.com/Alfresco/alfresco-content-app/assets/14104446/c2b4c43e-df52-4cfb-9cc6-0a8c966a74db)

**Comment by DenysVuika** [comment]
The `npm start -- configuration=adf` runs the linked ADF project that is cloned alongside the the ACA. typically you don't need ADF configuration unless you are changing both ADF and ACA components at the same time

**Comment by huyubao** [comment]
Yes, I have made changes to both ADF and ACA components

**Comment by DenysVuika** [comment]
But how the docker commands are related to this? You can run the "npm start -- --configuration=adf" to run the app.

**Comment by huyubao** [comment]
I have no problem running npm start configuration=adf, but running sh/ Docker/run content ce.sh deployed to Docker, webpage cannot be loaded

**Comment by DenysVuika** [comment]
Is there any particular reason for you using those scripts instead of just building and running the Dockerfile ? asking because those are the scripts used internally to host the app, and not documented. It requires the `.env` file with a bunch of variables present in your root.
