### ISSUE TITLE
Provide Angular version information on the Docs 

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-content-app#3222]
**Describe the bug**

In https://github.com/Alfresco/alfresco-content-app/blob/develop/docs/README.md provide Angular versions that are used for each ADF version. This can be added as an additional column.

**Comment by DenysVuika** [comment]
we have started tracking that in the root README.md: https://github.com/Alfresco/alfresco-content-app/blob/develop/README.md#compatibility you can find Node and ACS versions there too.
