### ISSUE TITLE
Default username and password

### ISSUE THREAD

**Issue by imsatoshi** [Alfresco/alfresco-content-app#3269]
I run "npm start" command. So what is the default username and password?

I tried admin but failed.

**Comment by DenysVuika** [comment]
the application sits on top of your ACS backend... the username and password are as those you have configured in the repository accounts. 

if you are using on the development machine, the README.md contains the environment variables you can use to simplify the running:

```
APP_CONFIG_ECM_HOST="<URL>"
```
