### ISSUE TITLE
Integration for PWA and service-worker

### ISSUE THREAD

**Issue by Alberto02001** [Alfresco/alfresco-content-app#3356]
**Is your feature request related to a problem? Please describe.**

Hi, we would like to integrate push notification libraries on ACA. Specifically we are looking to install **@angular/service-worker**.
We installed the library through the `npm i @angular/servicer-worker@14.1.3` command, then we added in the app/src/app/app.module file under the imports array the following configuration: 

```typescript
  imports: [
    BrowserModule,
    TranslateModule.forRoot(),
    CoreModule.forRoot(),
    SharedModule,
    CoreExtensionsModule.forRoot(),
    LoginComponent,
    environment.e2e ? NoopAnimationsModule : BrowserAnimationsModule,
    !environment.production ? StoreDevtoolsModule.instrument({ maxAge: 25 }) : [],
    RouterModule.forRoot(APP_ROUTES, {
      useHash: true,
      enableTracing: false, // enable for debug only
      relativeLinkResolution: 'legacy'
    }),
    AppExtensionsModule,
    ShellModule.withRoutes({
      shellChildren: [CONTENT_LAYOUT_ROUTES]
    }),
    ContentServiceExtensionModule,
   // HERE THE CODE I ADD
    ServiceWorkerModule.register('ngsw-worker.js', {
      enabled: !isDevMode(),
      // Register the ServiceWorker as soon as the application is stable
      // or after 30 seconds (whichever comes first).
      registrationStrategy: 'registerWhenStable:30000'
    })
  ],
```

Finally we added the file app/ngsw-config.json with the following code: 

```json
{
  "$schema": "./node_modules/@angular/service-worker/config/schema.json",
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/manifest.webmanifest",
          "/*.css",
          "/*.js"
        ]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**",
          "/*.(svg|cur|jpg|jpeg|png|apng|webp|avif|gif|otf|ttf|woff|woff2)"
        ]
      }
    }
  ]
}
```

At this point we run the application but at the time of the request for the Subscription object containing the endpoint, the browser returns the error: 

```
zone.js:372 Error: Service workers are disabled or not supported by this browser
    at SwPush.requestSubscription (service-worker.mjs:214:35)
```
i used this code on mine typescript component:

```typescript

  constructor(private swPush:  SwPush) { }

  webPushSubscription(){

      this.swPush.requestSubscription({
        serverPublicKey: "BF866nFihQoIBmOey0rOsDmvK2TYuSU3vKswY-I5oLE6BQQMliadg39a5TKJGfpNtinjtvn2xXajPU9j-3B0qkU"
      })
      .then(subcription => {
        console.log(JSON.stringify(subcription));
      })
      .catch(console.error);

      this.swPush.messages.subscribe((mes : any) => {
        console.log(mes);
      })
  }

```

what i'm doing wrong?

**Describe the solution you'd like**
I would like to be able to add the pwa feature as it is added in angular base projects with the following command: "ng add @angular/pwa", whereas with the current NX framework I have difficulty applying it.

**Describe alternatives you've considered**

**Additional context**
ACA version: 4.1.0

used dependencies:

  "dependencies": {
    "@alfresco/adf-content-services": "6.2.0",
    "@alfresco/adf-core": "6.2.0",
    "@alfresco/adf-extensions": "6.2.0",
    "@alfresco/eslint-plugin-eslint-angular": "6.2.0",
    "@alfresco/js-api": "6.2.0",
    "@angular/animations": "14.1.3",
    "@angular/cdk": "14.1.3",
    "@angular/common": "14.1.3",
    "@angular/compiler": "14.1.3",
    "@angular/core": "14.1.3",
    "@angular/forms": "14.1.3",
    "@angular/material": "14.1.3",
    "@angular/material-moment-adapter": "14.1.3",
    "@angular/platform-browser": "14.1.3",
    "@angular/platform-browser-dynamic": "14.1.3",
    "@angular/router": "14.1.3",
    "@angular/service-worker": "^14.1.3",
    "@asymmetrik/ngx-leaflet": "^14.0.1",
    "@fontsource/open-sans": "^5.0.3",
    "@fullcalendar/angular": "^6.1.8",
    "@fullcalendar/core": "^6.1.8",
    "@fullcalendar/daygrid": "^6.1.8",
    "@fullcalendar/interaction": "^6.1.8",
    "@fullcalendar/list": "^6.1.8",
    "@fullcalendar/timegrid": "^6.1.8",
    "@mat-datetimepicker/core": "^10.1.1",
    "@mat-datetimepicker/moment": "^10.1.1",
    "@ngrx/effects": "^14.2.0",
    "@ngrx/router-store": "^14.2.0",
    "@ngrx/store": "^14.2.0",
    "@ngrx/store-devtools": "^14.2.0",
    "@ngx-translate/core": "^14.0.0",
    "@types/leaflet": "^1.9.1",
    "chart.js": "^4.2.1",
    "date-fns": "^2.30.0",
    "dom-to-image-more": "^2.15.0",
    "file-saver": "^2.0.5",
    "html2canvas": "^1.4.1",
    "leaflet": "^1.9.4",
    "material-icons": "^1.13.8",
    "minimatch-browser": "^1.0.0",
    "moment": "^2.29.4",
    "moment-es6": "1.0.0",
    "ngx-editor": "^11.1.1",
    "ngx-webstorage": "^10.0.1",
    "pdfjs-dist": "3.3.122",
    "rxjs": "6.6.6",
    "tslib": "^2.5.3",
    "zone.js": "0.11.8"
  },
  "devDependencies": {
    "@alfresco/adf-cli": "6.2.0",
    "@alfresco/adf-testing": "6.2.0",
    "@angular-devkit/build-angular": "14.2.11",
    "@angular-devkit/core": "14.1.2",
    "@angular-devkit/schematics": "14.1.2",
    "@angular-eslint/builder": "^14.1.2",
    "@angular-eslint/eslint-plugin": "^16.0.2",
    "@angular-eslint/eslint-plugin-template": "^16.0.2",
    "@angular-eslint/schematics": "14.4.0",
    "@angular-eslint/template-parser": "^15.2.1",
    "@angular/cli": "14.1.3",
    "@angular/compiler-cli": "14.1.3",
    "@angular/language-service": "14.1.3",
    "@cspell/eslint-plugin": "^6.31.1",
    "@nrwl/angular": "15.9.2",
    "@nrwl/eslint-plugin-nx": "^15.9.2",
    "@nrwl/workspace": "15.9.2",
    "@playwright/test": "^1.35.0",
    "@schematics/angular": "14.1.2",
    "@types/event-emitter": "^0.3.3",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^14.14.12",
    "@types/selenium-webdriver": "^4.0.9",
    "@types/superagent": "^4.1.10",
    "@typescript-eslint/eslint-plugin": "^5.59.0",
    "@typescript-eslint/parser": "^5.48.2",
    "ajv-cli": "^4.2.0",
    "cypress": "^12.14.0",
    "dotenv": "8.2.0",
    "dotenv-expand": "^5.1.0",
    "envsub": "^4.1.0",
    "eslint": "^8.42.0",
    "eslint-plugin-ban": "^1.6.0",
    "eslint-plugin-import": "2.27.5",
    "eslint-plugin-jsdoc": "43.2.0",
    "eslint-plugin-license-header": "^0.6.0",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-rxjs": "^5.0.2",
    "eslint-plugin-unicorn": "^46.0.0",
    "husky": "^8.0.2",
    "jasmine-core": "~4.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "^6.4.1",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^3.0.3",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "karma-mocha-reporter": "^2.2.5",
    "lint-staged": "^13.1.0",
    "ng-packagr": "^14.2.2",
    "node-stream-zip": "^1.14.0",
    "nx": "15.9.2",
    "prettier": "2.8.8",
    "protractor": "~7.0.0",
    "protractor-retry-angular-cli": "^2.0.3",
    "protractor-screenshoter-plugin": "0.10.3",
    "protractor-smartrunner": "^2.0.0-beta6",
    "selenium-webdriver": "^4.1.1",
    "stylelint": "^15.6.3",
    "stylelint-config-standard-scss": "^7.0.1",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "4.2.0",
    "typescript": "4.7.4",
    "webdriver-manager": "12.1.8"
  }

**Comment by DenysVuika** [comment]
We don't declare support for PWA and service workers in ACA, so configuring the application with PWA is your responsibility, or task. You can check existing solutions https://github.com/nrwl/nx/discussions/7183 or search for some other approaches, but this is out of the ACA scope so far.
