### ISSUE TITLE
Button Texts overlapping and whitespace issues

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-content-app#3404]
**Describe the bug**
In the metadata tab, there are some issues. There is missing whitespace, which looks a bit weird. And labels for the Buttons to save or disregard changes are overflowing:

![Screenshot 2023-08-25 at 12 01 18](https://github.com/Alfresco/alfresco-content-app/assets/43036408/4f265292-bfad-4352-8512-2d5a81cabfd2)
 
Here is another example: 

![Screenshot 2023-08-25 at 12 07 26](https://github.com/Alfresco/alfresco-content-app/assets/43036408/5ac66f8c-038c-4029-b63a-a43cb0298bfc)

**Environment**
- ACA version: 4.1
- ACS version: 7.4

**Expected behavior**
Labels shouldn't overlap buttons and the text also shouldn't be cut off, no matter the length of the text.

Plus in the tabs, there should be whitespace/padding at the top.

**Desktop (please complete the following information):**
 - Browser Chrome, Safari, Firefox

**Comment by DenysVuika** [comment]
With latest redesign of the Properties panel, should no longer be an issue:

<img width="362" alt="Screenshot 2024-01-08 at 8 02 42 PM" src="https://github.com/Alfresco/alfresco-content-app/assets/503991/9b51317b-8e4f-4300-aa26-d8299f8c652a">
