### ISSUE TITLE
Add permissions displaying Site Permissions outside of Sites

### ISSUE THREAD

**Issue by morgan-patou** [Alfresco/alfresco-content-app#3411]
**Describe the bug**
I have an Alfresco Repository with custom permissions at the Repository layer (READ, WRITE, DELETE, SECURITY) while the sites have the default (Site Collaborator, Site Manager, ...). It appears that when there is a folder whose name is contained inside the name of a Site, then all documents / folders inside this problematic folders will have the wrong permissions being displayed to the user when he tries to add local permissions.

**Environment**
- ACA 4.1.0
- ACS 7.3.1

**To Reproduce**
1. Login with admin to get access to the /Company Home
2. Create a site "dbi services" (id: "dbi-services") -- I assume it should work with other names, it's just that I was trying to setup some playground for ACA and I used our company name to make things easier
3. Create a the folders /Company Home/Folder1/dbi/Folder2
4. Try to change the permissions on Folder2 and it seems that it will display the Site Manager / Site Collaborator / ... instead of the standard repo roles
5. Rename the folder "dbi" with "renamed_dbi" and the issue on Folder2 will be gone

**Expected behavior**
Correct roles should be presented to the user when he is outside of a site

**Screenshots**
Site:
![image](https://github.com/Alfresco/alfresco-content-app/assets/9655030/a4286de5-ae11-4183-9c55-f3ce758d56fd)

Before rename:
![image](https://github.com/Alfresco/alfresco-content-app/assets/9655030/64511919-acea-4b9f-889a-d0f9aed313f5)

After rename:
![image](https://github.com/Alfresco/alfresco-content-app/assets/9655030/648f0cfa-9326-46e5-9a3b-351fc7234d39)

**Desktop (please complete the following information):**
 - MacOS 13.4.1
 - Firefox 116.0.3

**Comment by DenysVuika** [comment]
From your screenshot, it seems that the roles are correct but not translated. Is that correct?

**Comment by aborroy** [comment]
That may be a secondary error. The main problem here is that using a folder name that is taken as Site Name provokes that permissions on the folder are associated to Site instead of to the expected ones for the node location.

**Comment by morgan-patou** [comment]
The display name isn't the problem. It's not translated because I didn't do anything to have them translated.

As @aborroy mentioned (see the "**Describe the bug**" section of the initial message), whenever you have a folder anywhere inside the Company Home that has a name (e.g. "dbi") that is the same as the starting name of a Site (e.g. "dbi services"), then the permissions on that Folder are Site Permissions and not simple Node Permissions.
