### ISSUE TITLE
The adf-content-metadata-card does not refresh to show the new values set for properties

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/alfresco-content-app#349]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using the preview component to read a document, if any property is changed using the embedded adf-content-metadata-card, once the user clicks the save button, the change is not reflected in the properties panel.
In order to see the new value, the user has to refresh the page.
Not even hiding and showing the info panel again solves the problem.

## Expected behavior
Once the user clicks save, the new value should be presented into the adf-content-metadata-card.

## Minimal reproduction of the problem with instructions
Open any document using preview, and then use the adf-content-metadata-card to change any property value.

## Environment

<pre><code>
alfresco-content-app version 1.2.0

Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Edge version XX
- [ ] IE11
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by john-knowles** [comment]
Thank you for raising this bug @douglascrp.  There are tickets in the backlogs for both the Content App project and the ADF. You will these this resolve in the next release.

**Comment by john-knowles** [comment]
This issue is not reproducing in 1.3
