### ISSUE TITLE
Permissions manager should not be showed for smart folder results.

### ISSUE THREAD

**Issue by AlgoJerViA** [Alfresco/alfresco-content-app#3491]
**Describe the bug**
The Permissions and Manage Rules options are available when right-clicking on a smart folder result.
If we press any of them we will apply changes to the virtual node and not to the actual node itself.
In share, the option to edit permissions and manage rules was simply removed.

**Environment**
- ACA version: 4.3.0
- ACS version: 6.4.0-6497510485

**To Reproduce**
1. Set up a smart folder. (I had folders as results)
2. Right-click on a folder and press Permissions
3. See some strange permissions and also lock at the URL to see it is the virtual node.

**Expected behavior**
There should be a rule to block Permission and Rules Manager in a smart folder.

**Comment by AlgoJerViA** [comment]
Another option is of course to redirect to the actualNodeRef instead. That is perhaps better.

**Comment by AlgoJerViA** [comment]
I have noticed more problems with smart folders.
It is generally never possible to edit any property of a search folder result anywhere.

**Comment by dominikiwanekhyland** [comment]
Hi, it's fixed here: https://github.com/Alfresco/alfresco-content-app/pull/3580
