### ISSUE TITLE
A percentage sign (%) in the search breaks the app

### ISSUE THREAD

**Issue by MarcKoester** [Alfresco/alfresco-content-app#3886]
**Describe the bug**
When I try to search with a % sign. The search doesn't work and isn't responding after that.

**Environment**
- ACA version: 4.3.0
- ACS version: 23.1.0

**To Reproduce**
1. Go to '/search'
2. Enter "%" into search
3. See console error
4. Search for something else
5. Search doesn't respond anymore. You need to reload or navigate away and back to make it work again.

**Expected behavior**
A search for % should work.

**Screenshots**
![aca-search-bug](https://github.com/Alfresco/alfresco-content-app/assets/311780/ba28ff1a-ff07-424a-812c-2767b2cfca5d)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chrome, firefox

**Additional context**

**Comment by DenysVuika** [comment]
For reference, this line of code is failing: https://github.com/Alfresco/alfresco-content-app/blob/2ad1bccc2e898da30b941e1b1c122aef76cb900c/projects/aca-content/src/lib/components/search/search-results/search-results.component.ts#L132
