### ISSUE TITLE
Want to add a checkbox to the row of document list.

### ISSUE THREAD

**Issue by eliteluxury** [Alfresco/alfresco-content-app#426]
I would like to add a check box to document list component.
How can I customize a row of the document list?

**Comment by DenisVuyka** [comment]
We use issue tracker to raise bugs and feature suggestions. Please raise general questions in the [Gitter Chat](https://gitter.im/Alfresco/alfresco-ng2-components) or [Community Portal](https://community.alfresco.com/community/application-development-framework)
