### ISSUE TITLE
How to create an extension?

### ISSUE THREAD

**Issue by wolmos-mrbau** [Alfresco/alfresco-content-app#4299]
**Describe the bug**
According to the tutorial docs an extension can be created with the command `ng generate library my-extension` but the command fails with `Error: This command is not available when running the Angular CLI outside a workspace.` 
This might be because the angular.json file is missing. What is the correct process to create an ACA extension?

**Environment**
- ACA version: 5.2.0

**To Reproduce**
1. Clone repository
2. Run npm install
3. Run `ng generate library my-extension`

**Expected behavior**
An extension should be created

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by MichalKinas** [comment]
ACA started using NX and since then `angular.json` was removed, you can use nx generator to achieve the same result: `nx generate @nrwl/angular:library my-extension`

**Comment by wolmos-mrbau** [comment]
Thanks for the info. I found more recent documentation for Digital Workspace that can be adapted for ACA here:
[Create-your-first-ADW-extension](https://support.hyland.com/r/Alfresco/Alfresco-Digital-Workspace/5.2/Alfresco-Digital-Workspace/Develop/Build-extensions/Create-your-first-ADW-extension)
It would still be good if the tutorials and documentation were brought up to date.

**Comment by MichalKinas** [comment]
Yes that's a good point, I will create a ticket to update them, thanks
