### ISSUE TITLE
Use ACA Components in a seperate Module not supported

### ISSUE THREAD

**Issue by boneill** [Alfresco/alfresco-content-app#542]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Cannot use existing ACA Components in a new Module

## Expected behavior

I would like to be able to create a module to group functionality and views for a use case.  In my case it is a module to manage organisations outside of Alfresco.  The aca components such as aca-info-drawer should be available within my new module to use.  

## What is the motivation / use case for changing the behavior?

Ability to use aca components and directives in an extension module for the aca application.

## Environment
aca 2.4, ACS 5.2
<pre><code>
ACA version: X.Y.Z

Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Edge version XX
- [ ] IE11
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by DenisVuyka** [comment]
The info drawer is already a separate module as per 1.4 (development branch): https://github.com/Alfresco/alfresco-content-app/tree/development/src/app/components/info-drawer
