### ISSUE TITLE
"More information" and "Less information" is shown incorrectly.

### ISSUE THREAD

**Issue by buimichael** [Alfresco/alfresco-content-app#632]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Properties panel shows "More information" when already expanded and "Less information" when collapsed.

## Expected behavior

Properties panel should show "More information" when metadata is collapsed and "Less information" when expanded.

## Minimal reproduction of the problem with instructions

Upload a document.
Preview the document.
Click view details
Properties (this is expanded by default)
![img](https://i.gyazo.com/cbb4ae268fc91239a6ef99b179e6136f.png)
![img](https://i.gyazo.com/9fae32f6935c950e68bc7ac2ddf54b26.png)

## What is the motivation / use case for changing the behavior?

Because it's incorrect

## Environment
<pre>ACA 1.4.0<code>

Browser:
- [64.0.3282.186] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Edge version XX
- [ ] IE11
 
For Tooling issues:
- Node version: 8.11.3  
- Platform:  Linux 

Others:

</code></pre>

**Comment by DenisVuyka** [comment]
Based on the current ADF rules, you always see "Properties" group, and extra groups defined via configuration file. When you click "More Information", the Properties gets collapsed, but you don't see extra stuff. That provides a feeling that you you see incorrect icon/text on the button.

We probably need to hide this button when no extra categories available, but it's not controlling the Properties one.

**Comment by john-knowles** [comment]
Closing this issue, the fix was delivered via changes in the ADF.

![less info](https://user-images.githubusercontent.com/18680913/51311614-38398180-1a41-11e9-9a63-d83d45d7619f.png)
![more info](https://user-images.githubusercontent.com/18680913/51311615-38398180-1a41-11e9-9e2d-49385f7bfd66.png)
