### ISSUE TITLE
ng Build Failure

### ISSUE THREAD

**Issue by aniketdharia** [Alfresco/alfresco-content-app#652]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

/var/www/html/alfresco-content-app$ ng build
                                                                                          
Date: 2018-09-21T12:17:51.674Z
Hash: 46aef71c8f37814eec43
Time: 20015ms
chunk {main} main.js, main.js.map (main) 625 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 680 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 851 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 643 kB [initial] [rendered]

ERROR in src/app/extensions.module.ts(2,35): error TS2307: Cannot find module 'aca-dev-tools'.

## Expected behavior

/var/www/html/alfresco-content-app$ ng build
                                                                                          
Date: 2018-09-21T12:17:51.674Z
Hash: 46aef71c8f37814eec43
Time: 20015ms
chunk {main} main.js, main.js.map (main) 625 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 680 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 851 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 643 kB [initial] [rendered]

## Environment

<pre><code>
ACA version: X.Y.Z

Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Edge version XX
- [ ] IE11
 
For Tooling issues:
- Node version: XX   v6.12.3
- Platform:   Ubuntu

Others:

</code></pre>

**Comment by DenysVuika** [comment]
According to documentation (main readme and separate docs site) you need to run the app with the `npm start` command.

**Comment by aniketdharia** [comment]
@DenysVuika yep! was using earlier version and used the command got the error above then read the document after posting the issue.. :)
