### ISSUE TITLE
Unable to import adf-core

### ISSUE THREAD

**Issue by vprince1** [Alfresco/alfresco-content-app#885]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I make an extension and add an "import { AlfrescoApiService } from '@alfresco/adf-core’;” in my component, I get a compile error complaining about the absence of WebKitFileEntry type used by "node_modules/@alfresco/adf-core/utils/file-utils.d.ts”.

Looking at documentation in https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md, I see this WebKitFileEntry type has been removed in typescript 3.1. Since the OOTB package.json uses typescript version 3.1.6, I think the file-utils.d.ts file should not reference the type.

When I downgraded the angular version from 7.1.1 to 6.1.10 and the typescript version from 3.1.6 to 2.9.2, my extension with the adf-core import builds without any issues.

I get the following exception without updating the angular and typescript versions:
![image](https://user-images.githubusercontent.com/11996632/50367894-a4a78a80-0540-11e9-9ba5-6374f678a8d1.png)

## Expected behavior
adding "import { AlfrescoApiService } from '@alfresco/adf-core’;” in my extension and running a build should not throw the WebKitFileEntry type

## Minimal reproduction of the problem with instructions
1) clone the current ACA 1.6.0 app
2) follow the steps in https://aca-dev-docs.netlify.com/#/extending/redistributable-libraries to create a extension
3) Add the following lines
* Import adf-core <code>import { AlfrescoApiService } from '@alfresco/adf-core';</code>
* Update the constructor <code>constructor(alfApiService: AlfrescoApiService) { }</code>

4) Run command "npm run build:my-extension"

## What is the motivation / use case for changing the behavior?
I want to use the AlfrescoApiService in my extension.

## Environment

<pre><code>
ACA version: 1.6.0

Browser:
- [ x] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Edge version XX
- [ ] IE11
 
For Tooling issues:
- Node version: v11.0.0
- Platform:  Mac

Others:

</code></pre>

**Comment by DenysVuika** [comment]
Thanks for reporting this issue. It has already been fixed in the upcoming ADF 3.0.0 and ACA 1.7.0. Meanwhile, you can try the same workaround we have in ACA 1.6.0 - add a typings with the missing interface like this https://github.com/Alfresco/alfresco-content-app/blob/master/src/typings.d.ts

**Comment by vprince1** [comment]
Thanks for your response Denys. Since 1.6.0 already has WebKitFileEntry declared, is there anything I need to do when writing my extension library and importing adf-core?

**Comment by DenysVuika** [comment]
Try adding similar typings file with the interface into your project, should be enough

**Comment by vprince1** [comment]
I added the same typings.d.ts into my extension at "projects/my-extension/src/typings.d.ts" and I still get the same error when I build using command `npm run build:my-extension` from the ACA root folder. Should I update any tsconfig files, etc. I even tried to install using typings command `./node_modules/.bin/typings install --save --global file:./projects/my-extension/src/typings.d.ts` with no luck. Any pointers is appreciated.

**Comment by DenysVuika** [comment]
Alternatively, you can try to add your custom typings file into the TS config (include) section. See docs on TS config. We can check some workarounds for 1.6 bit that will be after holidays

**Comment by DenysVuika** [comment]
The "development" branch with 1.7.0 is using latest ADF 3.x beta, and should work fine with the latest typescript.

**Comment by john-knowles** [comment]
@vprince1 - is this still an issue for you?

**Comment by vprince1** [comment]
I tried to rebase my development on master with my changes and I got the same error. I will take a clean development branch and add an extension and test and get back to you.

**Comment by vprince1** [comment]
@john-knowles @DenysVuika I was able to test this error does not occur in the development branch. Thanks
