### ISSUE TITLE
Allow sidebar items to be added dynamically

### ISSUE THREAD

**Issue by samuelengelen** [Alfresco/alfresco-content-app#898]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
At the moment, the extension mechanism enables the defining of navbar items in an extension.json file. This is static configuration.

## Expected behavior
It would be useful to allow items/links to be added dynamically (e.g. 'pinning' pages/items to the sidenav).

## What is the motivation / use case for changing the behavior?
Example: We want to enable end-users to save their search results as links in the sidenav. So when they are on a search results page, they could press a 'save search' button or similar, and the page link would appear in the sidenav. (Perhaps each user could have their own extension.json file, which is dynamically updated by a service?)

**Comment by john-knowles** [comment]
Thank you for the suggestion @samuelengelen 
We have created a ticket in our JIRA backlog (https://issues.alfresco.com/jira/browse/ACA-2154) and will consider this for a future release.

**Comment by DenysVuika** [comment]
In 1.8.0 we allow projecting custom components inside navbar. That should allow you to build a component that displays a list of links, and handles clicks on those links, for example.
