### ISSUE TITLE
Special characters in navBar item routes (extension.json) break the item link

### ISSUE THREAD

**Issue by samuelengelen** [Alfresco/alfresco-content-app#900]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Adding a route for navBar items in an extension.json file with special characters will result in an encoded url, and thus a broken link.

## Expected behavior
The url defined in the 'route' property of the extension.json file should also work with query parameters.

Either the elements of the route string from the json file should get parsed and passed in the correct way in the sideNav component (as queryParams/fragments), or the extension.schema.json should add the ability to define queryParams for a route. (=> this will probably have an impact on https://issues.alfresco.com/jira/browse/ACA-215)

## Minimal reproduction of the problem with instructions
In an extension.json file, define a route with special characters. 

```
"navbar": [
      {
        "id": "app.navbar.primary",
        "items": [
          {
            "id": "app.navbar.testLink",
            "order": 100,
            "icon": "extension",
            "title": "Test link",
            "description": "Test link",
            "route": "search;q=test"
          }
       ]
      }
     ]
```

In the Content App, click on the link. The special characters in the url will get encoded and lead to a broken link.

## What is the motivation / use case for changing the behavior?
We need to store links to specific searches, which include query parameters.

## Environment

<pre><code>
ACA version: 1.6.0

Browser:
- [x] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Edge version XX
- [ ] IE11

**Comment by DenysVuika** [comment]
made Jira issue public

**Comment by samuelengelen** [comment]
@DenysVuika That's what I thought. Your second suggestion could certainly work for our use case, and it would be relatively easy to implement a saved search (pinning pages to sidenav) mechanism with this solution.

**Comment by DenysVuika** [comment]
Yes, we are planning an alternative solution that involves "click" support for navbar entries, so that anyone can provide custom handlers
