### ISSUE TITLE
Overwrite default AuthGuard using extensions [Kerberos]

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#912]
Provide ability to override the default "AppAuthGuard" in app.routes.ts file with extension module. Currently we can configure the auth guards for the new routes but can't override the default auth guard. This provides more flexibility in handling the authentication.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

We have configured kerberos (using withCredentials) and has written custom auth guard to prevent users to redirect to login screen. In this case we have to modify the default auth guard in app.routes.ts file.  We don't see an option to override the default auth guard using extensions. 

## Expected behavior
We should be able to override the auth guard without modifying the default app.routes.ts file. 
## Environment
Content app 1.6.0
<pre><code>
ACA version: 1.6.0
Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Edge version XX
- [ ] IE11
 
For Tooling issues:
- Node version: 9.5.0 
- Platform:  Mac/ Windows / Linux

</code></pre>

**Comment by eromano** [comment]
with ADF 3.0.0 if withCredentials is true the normal guard is disabled automatically you don't need to change anything

**Comment by DenysVuika** [comment]
Closing the task as ADF 3.0.0 already supports required behavior.
