### ISSUE TITLE
Disable login redirect for Kerberos(withCredentials)

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#913]
If content services is configured with Kerberos, we don't need to redirect user to login / logout screens. All the apis are automatically authenticated with kerberos using "withCredentials". So in this case we need to modify the default auth guard to achieve this.  Provide this with some kind of configuration

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently even we enable "withCredentials" we have to override auth guard for the user to navigate to the app without login page.

## Expected behavior

If we enable "withCredentials" user has to be redirected directly to the application as he doesn't need to login manually to the app.

## Environment

<pre><code>
ACA version: X.Y.Z

Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Edge version XX
- [ ] IE11
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by john-knowles** [comment]
Logged in JIRA: https://issues.alfresco.com/jira/browse/ACA-2133

**Comment by DenysVuika** [comment]
Jira ticket: [ACA-2211](https://issues.alfresco.com/jira/browse/ACA-2211)

**Comment by binduwavell** [comment]
Denys, I can’t get to this JIRA either.
