### ISSUE TITLE
Impossible to define relative routes in navbar configuration

### ISSUE THREAD

**Issue by samuelengelen** [Alfresco/alfresco-content-app#919]
**Describe the bug**
When including a route/path for a sidenav item, it automatically gets changed into an absolute route/path. It seems the extension service adds a slash in front of every route defined in the extension jsons. Seems like a responsibility for the developer to add this slash in the json if that's what they want.

**To Reproduce**
1. In the navbar configuration of app.extension.json (or your own custom extension json), define a NavBarLinkRef with a relative route (e.g. './details').
2. In the app, click on the link.
3. Instead of '/details' being added to the current url, it is transformed to an absolute path and you'll land on the error page.

**Expected behavior**
When defining a relative path, I would expect it to behave as a relative path.

**Desktop (please complete the following information):**
 - OS: [OSX]
 - Browser [chrome]

**Comment by DenysVuika** [comment]
@samuelengelen thanks for reporting, I think the issue with the 'root' is here: https://github.com/Alfresco/alfresco-content-app/blob/development/src/app/extensions/extension.service.ts#L262

**Comment by pionnegru** [comment]
@samuelengelen 
Can you try using the '[parent]/details' over './details'?

**Comment by samuelengelen** [comment]
@pionnegru 
I just tried it, but unfortunately, [parent] gets interpreted as a string, and the brackets get escaped...

**Comment by pionnegru** [comment]
@samuelengelen 
apologies, should be ''parent/details', without []

**Comment by DenysVuika** [comment]
We are introducing support for click actions for navbar links. That should allow you to support different scenarios in code rather than moving complex logic to the JSON.
