### ISSUE TITLE
Responsiveness in General

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-content-app#926]
**Current behaviour**
Using the Content-App and the ADF Components I noticed there are many things not responsive. I have collected some things, using an iPhone 5 screen, since it's one of the smallest screen(even though the issues I have found also occur with bigger phones). 

Keep in mind, these are just my findings, there may be more issues with other components. Maybe a full test round needs to happen, and also maybe integrate some kind of automatic test / Pull request requirement to ensure new developments won't break responsiveness.

The problem is, as a developer you currently need custom CSS fixes, which can break with the next releases, so it would be better to have them inside the ADF/Content-App code.

Here is the corresponding ADF issue: https://github.com/Alfresco/alfresco-ng2-components/issues/4298

### Toolbar

https://drive.google.com/open?id=1H-O51SvUphsKGeU1ucTPO49KhPNH7m1r

As you can see in the screenshot, the searchbar presses the UserInfoComponent to the right side and it gets cut off.

### Search Results

https://drive.google.com/open?id=1kSbrtnao0TYWV30kurVjFI07HXRQ_oqE

The filter is visible but not the search results themselves. Maybe a floating action button for toggling the filter would be solution.

### Empty Info

https://drive.google.com/open?id=15RCI8NsjB26ib5aQKgbHz7rq1NLOw4P7

The message for when a user is inside an empty folder or similar gets cut by the screen.

### Breadcrumbs

https://drive.google.com/open?id=1H-O51SvUphsKGeU1ucTPO49KhPNH7m1r

Breadcrumbs become useless at a certain resolution and with a node selected. in the Screenshot you can see there are only dots left from the text-ellipsis. Maybe move it it's own bar or at the bottom.

**Comment by john-knowles** [comment]
https://issues.alfresco.com/jira/browse/ACA-2215

**Comment by DenysVuika** [comment]
I suggest providing a contribution for the CSS and responsiveness, if you already know how this should work and tested. Closing for now.
