### ISSUE TITLE
Sidemenu can't be closed on certain devices

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-content-app#928]
**Describe the bug**
When using a smartphone device with a small screen, for example the iPhone 5 SE you can't close the sidemenu, since it is taking the full screen space. You can only close it by going back (in the browser at least) or by choosing a menu item.

**To Reproduce**
1. Login
2. Open side menu
3. Can't be closed

**Expected behavior**
Side menu should be closeable on all resolutions. On bigger screens there is the background of the main content, where you can click to close it.

Maybe introduce a close icon/ button, which does exactly that.

**Screenshots**

Big device: https://drive.google.com/open?id=17uwbbD_6y7wlf_RZhXHUjXgOu6yrCXyl
Small device: https://drive.google.com/open?id=1MXAqo55QysjAqhuIldIWYKj5yyukW5S1

**Comment by DenysVuika** [comment]
@MariusGrunenberg What do you think if we provide a "swipe left" event on the sidebar to close it on mobile devices? should not then have issues with the "click outside" handler

**Comment by DenysVuika** [comment]
JIRA: https://issues.alfresco.com/jira/browse/ACA-2208

**Comment by MariusGrunenberg** [comment]
@DenysVuika 
That's a good idea. Though I don't know of a UX point of view, some users may not know that they need to swipe.

**Comment by DenysVuika** [comment]
I agree. It needs to be a combination of two things - swipe + gap to click away. Just checked how mobile Drive behaves and it always leaves some space to the right.

**Comment by MariusGrunenberg** [comment]
Yes i guess that would be perfect.

**Comment by DenysVuika** [comment]
Closing as done. We added both swipe left and click out support (https://github.com/Alfresco/alfresco-content-app/pull/934)
