### ISSUE TITLE
Application SDK library project

### ISSUE THREAD

**Issue by DenysVuika** [Alfresco/alfresco-content-app#930]
**Is your feature request related to a problem? Please describe.**

Extension libraries cannot have Application as a dependency, and there is no way to reuse common/shared application components from within external libraries.

For example, an extension cannot inherit PageComponent to build a DocumentList-friendly page,
all NgRx types and effects are not accessible too (though can be invoked in a generic/untyped way).

**Describe the solution you'd like**

- Move reusable extensibility content to the ADF level
- Create a separate Application SDK library project that contains a shared/reusable content from the application (reusable content that makes sense only within ACA/ADW)
- Allow Application and Extensions reference it to solve circular dependency issues. 
- Publish SDK library to NPM to allow better upgrades and simplify Digital Workspace integration

**Describe alternatives you've considered**

Note that all cross-project content will be moved to the ADF level. This feature request is about ACA-specific implementations.

**Additional context**

Things to move to an application SDK level in the first iteration:

- NgRx: actions, effects, selectors
- Components and UI building blocks: PageComponent, etc
- Extensibility: app-specific rules, evaluators, interfaces

Corresponding Jira ticket: [ACA-2196](https://issues.alfresco.com/jira/browse/ACA-2196)

**Comment by binduwavell** [comment]
I really hope this will make it into a version of ACA that is compatible with ACS 5.2 :)

**Comment by nvmadhav** [comment]
ya we are also using ACS 5.2 and it will take a while to upgrade to 6.0. I requested the same ticket in ACA and hope this fix compatible with ACS 5.2

**Comment by john-knowles** [comment]
The delta on ACS REST APIs between 5.2 and 6 is too large to provide compatibility.

**Comment by nvmadhav** [comment]
How do we know the list of components get impacted if we use ACA On ACS 5.2?so far we are using 5.2 version and don’t see any specific issues . What will be the direction going forward for the users using ACA 5.2?

**Comment by DenysVuika** [comment]
@binduwavell, @nvmadhav this ticket is about splitting the application into separate libs, not about ACS.

**Comment by ohej** [comment]
I really support the idea of having reusable parts of the app especially considering extensions. 

Would this also contain layout/css, or would that still be contained within ACA? I wonder if there is value in using this without ACA? What if I'm building an ADF app (non ACA/ADW based), wouldn't it still be valuable to leverage some of this for layout/functionality purposes?

Not trying to have more stuff creep into the scope, but it's worth exploring if this could be valuable as a generic library for ADF development, or if it's purely ACA/ADW related.

**Comment by DenysVuika** [comment]
@ohej The intention is to move all the generic stuff to ADF level (we are already in progress doing that). And moving only app-specific things to the separate library, like some specific NgRx stuff. If there's something one can use without ACA then for sure it should be in the ADF.

**Comment by ohej** [comment]
That makes sense. This is really a no-brainer that we should do for 1.8.

**Comment by binduwavell** [comment]
Denys, I posted version concerns on gitter and on the issue you linked above.
