### ISSUE TITLE
Version compatibility matrix

### ISSUE THREAD

**Issue by DenysVuika** [Alfresco/alfresco-content-app#932]
**Is your feature request related to a problem? Please describe.**
It is not clear what versions of ACS/APS does a particular version of ACA support.

**Describe the solution you'd like**
Provide compatibility matrix similar to the one of ADF: [example](https://github.com/Alfresco/alfresco-ng2-components/blob/development/docs/compatibility.md)

**Additional context**
Corresponding Jira ticket: [ACA-2203](https://issues.alfresco.com/jira/browse/ACA-2203)

**Comment by binduwavell** [comment]
Posting comment from gitter here... It is going to be a good while before a significant portion of your user base is on 6.x. I’m asking that we have a version of ACA with extensions that works with 5.2 for a good long while. If this requires ACA to perform version detection and hide new features, that would be fine. But blazing forward assuming folks are on 6.x is going to hamper adoption of ADF and ACA in the existing install base, which likely is the larger audience for these things than net new or folks who have upgraded to 6.x.

**Comment by john-knowles** [comment]
Have started populating a table in ACA-2203

**Comment by john-knowles** [comment]
@nvmadhav in reply to your comment on #930

> How do we know the list of components get impacted if we use ACA On ACS 5.2?so far we are using 5.2 version and don’t see any specific issues . What will be the direction going forward for the users using ACA 5.2?

The REST API delta between 5.2 and 6.0 that I referred to has an affect at the application level, for example:
- REST API for knowing if a user is ADMIN or not enables the app to show/hide the Deleted by column in Trash, it also helps show a more sensible breadcrumb for admin who does not have a personal files area
- Range request support in the API saves the app from having to download whole video and audio files before playing can commence
- Nodes API includes isFavorite information so the app can display whether a file is a favorite when the document list is loaded
- Relative path information also help with the construction of the breadcrumb

It is likely you will find that version 1.6 of the app mostly works "fine" with ACS 5.2, but there will be some subtle features that may not behave the same.

**Comment by nvmadhav** [comment]
Thank you for the details. What about version 1.7? We are currently testing the version from ACA development as it has fixes and new functionalities. Do you have the list of features which might get impacted if we use ACA 1.7 with ACS 5.2? This is really needed as I assume most of the enterprise clients are on 5.2 still and require good time to moce to 6.0. At the same time we really needed the features of ACA1.7 including extensions framework. Let us know your thoughts

**Comment by john-knowles** [comment]
Edit Offline, and Edit in Office are the main features coming in 1.7 and those don't rely on API changes in ACS 6.1

SSO via Alfresco Identity Service is ACS 6.1+ only.

**Comment by nvmadhav** [comment]
So that means we can safely use ACA1.7 with ACS 5.2 if we are not using SSO via identity service?

**Comment by john-knowles** [comment]
Sounds like it, if your current testing covers ACA 1.6 and ACS 5.2. We do not test this project against ACS 5.2 since April/May 2018.

**Comment by binduwavell** [comment]
John, would you consider starting to perform testing of this project against 5.2 and taking actions to assure a good experience for customers on 5.2?

**Comment by john-knowles** [comment]
There are no plans to make the application fully backwards compatible with older versions of ACS.

**Comment by binduwavell** [comment]
John, I’m asking you to consider making such plans :)

**Comment by DenysVuika** [comment]
Actual matrix is going to be part of the main [GitHub readme](https://github.com/Alfresco/alfresco-content-app/tree/development#compatibility) starting with 1.7.
