### ISSUE TITLE
Menu item showing as "Favorite" for already favorited items

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#944]
**Describe the bug**
When we select the file and click on Favorite in the context menu. Then when you right click , you still see the "Favorite" option in the context menu. Ideally we should see the "UnFavorite" option
**To Reproduce**
1. Go to a document / folder 
2. Click on the document / folder
3. Select "Favorite" option
4. The document / folder will be set as favorite. 
5. Click on the document again and you still see the favorite option. Ideally we should see the "Unfavorite" option here. Currently it does un favorite but this is confusing to the users as there is no other way they know whether the file got already favorited or not

**Expected behavior**
Ideally it should show unfavorite option. Also if we can have some symbol on the file which shows the file is favorited. Currently there is no way user knows whether file got favorited or not.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by john-knowles** [comment]
Thank you for the feedback - logged: https://issues.alfresco.com/jira/browse/ACA-2213
