### ISSUE TITLE
name change in properties requires a refresh

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#945]
**Describe the bug**
When user updates the name in the metadata panel, it still displays the old name in the document list. Ideally it should refresh the document list and display new name.
**To Reproduce**
1. Go to any document and open metadata panel
2. Modify the name of the document 
3. Page is not refreshed and user still sees the old name in the document list.

**Expected behavior**
Ideally user should see the new name in the document list.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DenysVuika** [comment]
We already have a PR for ADF 3.1 to enable dynamic reloads of document list cells. Hopefully, this feature will land in ACA 1.8.

**Comment by john-knowles** [comment]
https://issues.alfresco.com/jira/browse/ACA-1288
https://issues.alfresco.com/jira/browse/ADF-3794
