### ISSUE TITLE
Share link not functional

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#946]
**Describe the bug**
When we select a document and click on "Share" , the url provided there does not work for us.
**To Reproduce**
1. Go to  a document
2. Click on "Share" in the context menu
3. Copy the share url
4. If we browse the url, its not working. It redirects to the home page of the share. The below is the URL 
https://<<servername>>/#/preview/s/Jk6qSKsfSpiUVyOOuVNM5w

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pionnegru** [comment]
@nvmadhav 
is this related with https://alfresco-content-app.netlify.com/#/getting-started/configuration?id=shared-files-address config?

**Comment by nvmadhav** [comment]
we have not configured "baseShareUrl" so its taking it from "ecmHost" which is correct. In our case it takes the server url propertly but after that the url formed looks incorrect. Is this change specific to ACS6.0 as we use ACS 5.2.4 and share url looks dfferent from Alfresco share

**Comment by DenysVuika** [comment]
Note that we generate Angular route/url that looks similar to Share format, but is completely unrelated to Share.

**Comment by DenysVuika** [comment]
This is the [application route](https://github.com/Alfresco/alfresco-content-app/blob/master/src/app/app.routes.ts#L51) that handles Shared Preview, the ACA provides own preview of shared items.

**Comment by nvmadhav** [comment]
oh.then why the url getting constructed with "ecmHost". It should be from the ACA URL . Currently its constructing the url based on "ecmHost". Once I modify the url to point to ACA app then it works. Do I need to give in "baseShareUrl" again the aca app url?

**Comment by DenysVuika** [comment]
@nvmadhav that's a very good point. We usually have a proxy and run ACA + ACS + other apps on the same host. That should explain why this issue has not been found earlier, for devs it's always ACA app url.

**Comment by john-knowles** [comment]
Logged: https://issues.alfresco.com/jira/browse/ACA-2214

The work around is simply to populate the baseShareUrl with the apps URL see: https://alfresco-content-app.netlify.com/#/getting-started/configuration

**Comment by nvmadhav** [comment]
yes also looks like the "Download" functionality not working using shared url. When I go to Shared url, it displays the download icon but nothing happens when I click it.

**Comment by john-knowles** [comment]
Kerberos?

**Comment by nvmadhav** [comment]
Yes we use Kerberos authentication but I don't think this is related to kerberos as I don't see any call being made when I click download. Is this working in your environment?

**Comment by john-knowles** [comment]
Works in our production environment which is v1.6 but not our development environment; given the upgrade to ADF 3.0 (released today) is not complete I fully some regressions.  Will make sure we cover this one off.

**Comment by nvmadhav** [comment]
Thanks. ACA1.7 will be released next week?

**Comment by john-knowles** [comment]
By end of next week we'll have a target release date.

**Comment by nvmadhav** [comment]
Thanks

**Comment by john-knowles** [comment]
Regression bug logged: https://issues.alfresco.com/jira/browse/ACA-2216
