### ISSUE TITLE
Not able to view the text files [Kerberos]

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#947]
**Describe the bug**
File Preview not working for the text files
**To Reproduce**
1. Upload any text file
2. Click on the uploaded file
3. You will see blank page instead of the text file content

**Expected behavior**
Text file has to be displayed. And user should have option to edit inline
**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 22] ACS 5.2 & ACA 1.6 (latest from development)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DenysVuika** [comment]
Please give more details on the context, like ACS version used, ACA version, authentication mode, etc.
The ACA ships with the docker compose file that allows you to test the app with 6.1 community edition. does it reproduce there too?

**Comment by nvmadhav** [comment]
ACS 5.2 & ACA 1.6(latest from development)
authentication mode: Kerberos
I never tested through docker with 6.1

**Comment by nvmadhav** [comment]
I will check this and get back ..Probably this may be from our end.

**Comment by nvmadhav** [comment]
This call fails with 401 unauthorized. Probably issue related to "withCredentials" not being passed here.  
https://<<serverName>>/alfresco/api/-default-/public/alfresco/versions/1/nodes/d5cc1545-9a04-47f7-96b4-2220baabe9d0/content?attachment=false

**Comment by john-knowles** [comment]
@DenysVuika text files work fine in non-kerberos, is this an ADF issue?

**Comment by DenysVuika** [comment]
Might be an ADF text viewer issue but we can leave here and move to ADF once we are able to reproduce

**Comment by nvmadhav** [comment]
This issue is in ADF txtViewer.component.ts. Here looks like it directly uses http.get instead of using any alfrescoapi service. So here withCredentials is not being passed. Image viewers are working fine. Please move this ticket to ADF and make this addressed as this is a blocker.

**Comment by DenysVuika** [comment]
Closing as 1.8 should have this resolved with ADF 3.2
