### ISSUE TITLE
The Share Link dialog has unfriendly "copy" button.

### ISSUE THREAD

**Issue by DenysVuika** [Alfresco/alfresco-content-app#956]
**Is your feature request related to a problem? Please describe.**
When sharing a file, it's difficult to understand that the "link" icon is, in fact, a "copy url" button.

**Describe the solution you'd like**
Use traditional copy icon instead of the "link" icon to give users a clue that URL can be copied.

**Describe alternatives you've considered**
None

**Additional context**

<img width="605" alt="screenshot 2019-02-15 at 15 49 04" src="https://user-images.githubusercontent.com/503991/52868067-4232cb00-313a-11e9-9861-7acde5903b2c.png">

**Comment by binduwavell** [comment]
+1

**Comment by inavarre** [comment]
Added to Jira - https://issues.alfresco.com/jira/browse/ACA-3744
