### ISSUE TITLE
Edit in Office Icon

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#958]
**Describe the bug**
Please change the Icon of Edit in Office. Currently it displays MS-WORD Icon for both Word and Excel documents. Either it should show separate icons based on the file type (Word / Excel/ Powe POint) or a generic icon for Office.
**Environment**
- ACA version:1.6 ( from Development)
- ACS version: 5.2.4

**To Reproduce**
1. Go to a office document
2. Right Click on the document
3. See the Edit in Office Icon

**Expected behavior**
Icon shold be either generic or based on the file type
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DenysVuika** [comment]
It wil be covered by: https://github.com/Alfresco/alfresco-content-app/issues/935

**Comment by DenysVuika** [comment]
We switched to a generic icon for now in 1.7.0, thanks.
