### ISSUE TITLE
Generic Viewer route to invoke file preview

### ISSUE THREAD

**Issue by DenysVuika** [Alfresco/alfresco-content-app#961]
**Is your feature request related to a problem? Please describe.**
For the time being it's not easy to invoke a file preview from within the extensions.
The existing Preview component (ADF Viewer wrapper) is bound only to ACA-specific routes.

**Describe the solution you'd like**
Provide a generic "/viewer/<nodeId>" route that allows extensions invoking file preview.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by binduwavell** [comment]
Nice idea!

**Comment by DenysVuika** [comment]
We now support a new NgRx action "VIEW_NODE" that takes node id and provides an overlay viewer. Should be available with 1.8
