### ISSUE TITLE
Select all feature in the document list

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#965]
**Is your feature request related to a problem? Please describe.**
Currently we don't have option to select all the documents at once. We need to select one after the another. Provide the ability to select all the files / folders in the page
**Describe the solution you'd like**
Select all feature need to be provided. 

**Describe alternatives you've considered**

**Additional context**

**Comment by binduwavell** [comment]
Please consider both a UI option and a keyboard option.

**Comment by DenysVuika** [comment]
Document List supports "checkboxes" column and multi-selection, maybe a way to toggle that from the toolbar.

**Comment by john-knowles** [comment]
Keyboard controls are planned for the next version see https://issues.alfresco.com/jira/browse/ACA-878

**Comment by DenysVuika** [comment]
closing as enabled by default in the coming release
