### ISSUE TITLE
Add possibility to load custom template/sub-menus when navigating to some routes

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-content-app#982]
**Is your feature request related to a problem? Please describe.**
We would like to have a custom menu items or the possibility to load custom templates in the side nav menu based on conditions via the extensions.
For example : 
Navigate to /whatever
  -> show extra menu options 
OR
 -> load custom template component in the side nav.

**Describe the solution you'd like**
For extra menu options the rules should be re-evaluated on rerouting.

**Describe alternatives you've considered**

**Additional context**

**Comment by john-knowles** [comment]
Thank you @VitoAlbano - I have created https://issues.alfresco.com/jira/browse/ACA-2322 in our JIRA backlog.

**Comment by john-knowles** [comment]
Closed as part of https://issues.alfresco.com/jira/browse/ACA-2322
