### ISSUE TITLE
Analytics - Event tracking

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#992]
**Is your feature request related to a problem? Please describe.**
We need to track user clicks on documents / edit in ms office/ copy/ move kind of scenarios.

**Describe the solution you'd like**
Something like google analytics to have entire usage of analysis of the content applications from users perspective
**Describe alternatives you've considered**

**Additional context**

**Comment by DenysVuika** [comment]
It is possible to clone the ACA, modify the source code to add analytics and deploy locally.
