### ISSUE TITLE
Bottom sheet component for mobile context menu

### ISSUE THREAD

**Issue by DenysVuika** [Alfresco/alfresco-content-app#999]
**Is your feature request related to a problem? Please describe.**
Desktop-oriented context menus are not user-friendly when using mobile devices. 

**Describe the solution you'd like**
Provide support for Angular Material's [Bottom Sheet](https://material.angular.io/components/bottom-sheet/overview) when invoking context actions for nodes.

The "more" menus in the toolbars could invoke Bottom Sheet component as well.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by john-knowles** [comment]
Created JIRA backlog item for this: https://issues.alfresco.com/jira/browse/ACA-2658
